### ISSUE TITLE
Issue's when running tsoa with runtypes package

### ISSUE THREAD

**Issue by RobertoGeuke** [lukeautry/tsoa#1083]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
I'm using the [runtypes](https://github.com/pelotom/runtypes) package for runtime validation of objects coming from external inputs (e.g. mysql database). Because I don't want to define my types twice I want to convert the runtypes type to a regular Typescript type which will be used by tsoa. 

```ts
// model/mytype.ts
export const MyTypeSchema = Record({
    id: Number,
    name: String,
});

export type MyType = Static<typeof MyTypeSchema>;

// controller/mytype.ts
@Put()
public async updateMyType(
    @Body() requestBody: MyType,
    @Request() req: ExpressRequest,
    @Res() validationErrorResponse: TsoaResponse<422, ValidationErrorResponse>,
) {
    ...
}
```

## Current Behavior
If I try to generate my routes (programmatically or with the CLI) I receive the following error:

```
(node:30814) UnhandledPromiseRejectionWarning: Error: Unknown type: TypeQuery
At: /Users/anon/Work/publishing/cms/api/src/model/mytype.ts:60:60.
This was caused by 'Static<typeof MyTypeSchema>'
 in 'MyTypeController.updateMyType'
    at new GenerateMetadataError (/Users/anon/Work/publishing/cms/node_modules/@tsoa/cli/src/metadataGeneration/exceptions.ts:6:5)
    at /Users/anon/Work/publishing/cms/node_modules/@tsoa/cli/src/metadataGeneration/methodGenerator.ts:83:17
    at Array.map (<anonymous>)
    at MethodGenerator.buildParameters (/Users/anon/Work/publishing/cms/node_modules/@tsoa/cli/src/metadataGeneration/methodGenerator.ts:77:8)
    at MethodGenerator.Generate (/Users/anon/Work/publishing/cms/node_modules/@tsoa/cli/src/metadataGeneration/methodGenerator.ts:51:29)
    at /Users/anon/Work/publishing/cms/node_modules/@tsoa/cli/src/metadataGeneration/controllerGenerator.ts:52:35
    at Array.map (<anonymous>)
    at ControllerGenerator.buildMethods (/Users/anon/Work/publishing/cms/node_modules/@tsoa/cli/src/metadataGeneration/controllerGenerator.ts:52:8)
    at ControllerGenerator.Generate (/Users/anon/Work/publishing/cms/node_modules/@tsoa/cli/src/metadataGeneration/controllerGenerator.ts:41:21)
    at /Users/anon/Work/publishing/cms/node_modules/@tsoa/cli/src/metadataGeneration/metadataGenerator.ts:249:35
```

I'm not sure why this is happening. I thought maybe Typescript/tsoa can't find the `runtypes` `Static` type or maybe `tsoa` just is not compatible with `runtypes`. I'm also not sure how to resolve these issues. I want to use `tsoa`, but I have to find a way to make it work with `runtypes` or find a replacement to validate external input coming from other sources then the request.

## Context (Environment)

Version of the library: 3.11.0
Version of NodeJS: 14.17.4
Version of runtypes: 6.3.2

- Confirm you were using yarn not npm: [x]

**Comment by WoH** [comment]
These type queries are somewhat trickier to resolve, as they're only available as type information as provided by the type checker. But if someone wants to take a stab at this, I'd be happy to support this.
