### ISSUE TITLE
The @Example decorator doesn't work with Date constructor arguments

### ISSUE THREAD

**Issue by AudunWA** [lukeautry/tsoa#1125]
The `@Example` decorator doesn't work when providing Date objects with the `(year: number, month: number, date?: number, hours?: number, minutes?: number, seconds?: number, ms?: number)` constructor.
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
I expected the following example to be generated:

```json
"examples": {
	"Example 1": {
		"value": {
			"date": "2021-11-01T09:00:00.000Z"
		}
	}
}
```

The TypeScript code that would generate this json would be:
```ts
@Example<Data>({
	date: new Date(2021, 10, 1, 9, 0, 0, 0)
})
```

## Current Behavior
Currently, tsoa fails with the following error:
```
Generate routes error.
 RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at Object.getInitializerValue (.../node_modules/@tsoa/cli/src/metadataGeneration/initializer-value.ts:35:33)
    at .../node_modules/@tsoa/cli/src/metadataGeneration/initializer-value.ts:48:37
    at Array.forEach (<anonymous>)
    at Object.getInitializerValue (.../node_modules/@tsoa/cli/src/metadataGeneration/initializer-value.ts:47:32)
    at .../node_modules/@tsoa/cli/src/metadataGeneration/initializer-value.ts:12:51
    at Array.map (<anonymous>)
    at Object.getInitializerValue (.../node_modules/@tsoa/cli/src/metadataGeneration/initializer-value.ts:12:36)
    at .../node_modules/@tsoa/cli/src/metadataGeneration/initializer-value.ts:48:37
    at Array.forEach (<anonymous>)
```
## Possible Solution
By manually changing this part of `initializer-value.ts`:
```typescript
if (argsValue.length > 0) {
  date = new Date(argsValue as any);
}
```
to
```typescript
if (argsValue.length > 0) {
  // @ts-ignore
  date = new Date(...argsValue)
}
```
it works.

## Steps to Reproduce

1. Add the following `@Example` decorator to a endpoint in a controller:
```ts
@Example<Data>({
	date: new Date(2021, 10, 1, 9, 0, 0, 0)
})
```
2. Run `tsoa spec`
3. Observe that tsoa crashes.

## Context (Environment)

Version of the library: 3.11.2
Version of NodeJS: v14.17.0

- Confirm you were using yarn not npm: [ ]

## Breaking change?
I haven't tested with other variants of the Date constructor, so it might break some of those.

**Comment by AudunWA** [comment]
Not stale
