### ISSUE TITLE
Tsoa Getting started guide error - Generate routes error. Error: No declarations found for referenced type User

### ISSUE THREAD

**Issue by melvingaye** [lukeautry/tsoa#1222]
**Note** - I am using __npm__ instead of __yarn__ (I did read the note to use yarn ), if this isn't working because I am not using yarn, then I need to find an alternative to tsoa and it should be okay to close this ticket.

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit
 
I found https://github.com/lukeautry/tsoa/issues/340 and it did not seem to match exactly what I am doing (person was using external dependencies and my interfaces are part of my `/src`). I also read the proposed solution https://github.com/lukeautry/tsoa/issues/340#issuecomment-518229063 and that seems to be what I am doing.

## Expected Behavior

Following the https://tsoa-community.github.io/docs/getting-started.html guide, I was expecting a directory of routes and specs to be generated after running  `./node_modules/.bin/tsoa routes`. 

## Current Behavior

```
Generate routes error.
 Error: No declarations found for referenced type User.
    at new GenerateMetadataError (C:\Repos\JS\React\portfolio-site\server\node_modules\tsoa\node_modules\@tsoa\cli\dist\metadataGeneration\exceptions.js:22:28)
    at TypeResolver.getModelTypeDeclaration (C:\Repos\JS\React\portfolio-site\server\node_modules\tsoa\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:708:19)
    at TypeResolver.typeArgumentsToContext (C:\Repos\JS\React\portfolio-site\server\node_modules\tsoa\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:836:32)
    at TypeResolver.getReferenceType (C:\Repos\JS\React\portfolio-site\server\node_modules\tsoa\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:551:14)
    at TypeResolver.resolve (C:\Repos\JS\React\portfolio-site\server\node_modules\tsoa\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:367:34)
    at TypeResolver.resolve (C:\Repos\JS\React\portfolio-site\server\node_modules\tsoa\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:357:118)
    at MethodGenerator.Generate (C:\Repos\JS\React\portfolio-site\server\node_modules\tsoa\node_modules\@tsoa\cli\dist\metadataGeneration\methodGenerator.js:59:76)
    at C:\Repos\JS\React\portfolio-site\server\node_modules\tsoa\node_modules\@tsoa\cli\dist\metadataGeneration\controllerGenerator.js:60:58
    at Array.map (<anonymous>)
    at ControllerGenerator.buildMethods (C:\Repos\JS\React\portfolio-site\server\node_modules\tsoa\node_modules\@tsoa\cli\dist\metadataGeneration\controllerGenerator.js:60:14)
```

## Steps to Reproduce

1.  `npm i tsoa`
2.  Follow the steps here and replace yarn with npm https://tsoa-community.github.io/docs/getting-started.html
3.  Folder structure is different, instead of `/users` I have `/controllers`, `/services`, `/models` Gist - https://gist.github.com/melvingaye/e5c0be7a0e819b0aee0d41674962e2a6
4.  Finally when you reach the step to generate the routes, run `./node_modules/.bin/tsoa routes`.

## Context (Environment)

OS: Windows 10.
Version of the library: 3.14.1
Version of NodeJS: 14.15.5

- Confirm you were using yarn not npm: [ ]

I am using npm, if I have to use yarn for this then I will need to find an alternative solution.

**Comment by melvingaye** [comment]
Just did some more testing and it is not npm. I am doing something wrong with my setup , so this ticket is no longer needed.

**Comment by JavierSplvdArup** [comment]
I bet the problem is the non-relative import paths.
Try with `import { User } from '../models/user';` on your controller.

**Comment by connorjohnson85** [comment]
@melvingaye What was your solution? I'm running into  the same problem

**Comment by burki169** [comment]
I've run into same error with a simple type but @JavierSplvdArup's suggestion fixed the issue.
