### ISSUE TITLE
Not parsing APIGatewayProxyResult typescript types

### ISSUE THREAD

**Issue by blade2005** [lukeautry/tsoa#1223]
tsoa incorrectly parses typescripts from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/aws-lambda
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I want be able to generate the routes or swagger.

## Current Behavior

When generating routes(or any command) it has issues with the api-gateway-proxy types.
```
$ npx  tsoa routes
There was a problem resolving type of 'APIGatewayProxyResult'.
Generate routes error.
 Error: Unknown type: UndefinedKeyword
At: <redacted>/node_modules/@types/aws-lambda/trigger/api-gateway-proxy.d.ts:110:110.
This was caused by '{
        [header: string]: boolean | number | string;
    } | undefined'
    at new GenerateMetadataError (<redacted>/node_modules/@tsoa/cli/dist/metadataGeneration/exceptions.js:22:28)
    at TypeResolver.resolve (<redacted>/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:334:19)
    at <redacted>/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:116:95
    at Array.map (<anonymous>)
    at TypeResolver.resolve (<redacted>/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:115:45)
    at TypeResolver.propertyFromSignature (<redacted>/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:777:143)
    at <redacted>/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:743:161
    at Array.map (<anonymous>)
    at TypeResolver.getModelProperties (<redacted>/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:743:124)
    at TypeResolver.getModelReference (<redacted>/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:618:31)
```
sample code
```javascript
import { Get, Route, Response, SuccessResponse } from '@tsoa/runtime';
import { APIGatewayProxyEvent, APIGatewayProxyResult } from "aws-lambda";
import { BaseController } from "./base.controller";
import { inject, injectable } from "inversify";
import { HealthService } from "../services/health.service";
import { LoggerService } from "../services/common/logger.service";

@Route("Health")
@injectable()
export class HealthController extends BaseController {
  constructor(
    @inject(LoggerService) loggerService: LoggerService,
    @inject(HealthService) private healthService: HealthService
  ) {
    super(loggerService);
  }

  // @Response<null, HealthService.HealthServiceResult>(200, "Ok")
  @SuccessResponse('200', 'Returns HealthServiceResult')
  @Get()
  async getHealth(event: APIGatewayProxyEvent): Promise<APIGatewayProxyResult> {
    this.logger.trace("getHealth called", null, this.constructor.name);
```

The snippet it failing on
```javascript
export interface APIGatewayProxyResult {
    statusCode: number;
    headers?: {
        [header: string]: boolean | number | string;
    } | undefined;
    multiValueHeaders?: {
        [header: string]: Array<boolean | number | string>;
    } | undefined;
    body: string;
    isBase64Encoded?: boolean | undefined;
}
```

## Steps to Reproduce

1. 2. 3. 4.

## Context (Environment)

Version of the library: 3.14.1
Version of NodeJS: 17.7.1
npm version: 8.5.2

- Confirm you were using yarn not npm: [ ]

**Comment by Thutur39** [comment]
Hi ! I'm also facing this issue, did you find a workaround ? Thanks!
