### ISSUE TITLE
tsoa hangs over multiple lines when using utility-types

### ISSUE THREAD

**Issue by GalTidhar-Deliverr** [lukeautry/tsoa#1238]
When using a utility type [here](https://www.typescriptlang.org/docs/handbook/utility-types.html), for example Omit, if the array parameter breaks into multiple lines TSOA hangs indefinitely 
## Sorting

- **I'm submitting a ...**

  - [X] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

TSOA should understand the behavior when using[utilityTypes](https://www.typescriptlang.org/docs/handbook/utility-types.html) such as Omit

export interface FindUser extends Pick<User, 
'_id' | 
'name' | 
'dateOfBirth' | 
'height' | 
'nationality' | 
'citizenShip' | 
'username' | 
'link'> {
    id: string
}

## Current Behavior

When Prettify breaks the interface signature into multiple lines the typescript works fine but TSOA hangs indefently trying to generate routes and spec

## Steps to Reproduce
Just create a response object extending one of the utility types and put the strings in separate lines

1. 2. 3. 4.

## Context (Environment)
Version of the library:  3.14.0
Version of NodeJS: 17
typescript: 4.4.4

- Confirm you were using yarn not npm: [X]

**Comment by MML1357** [comment]
I got the same behavior using tsoa v4.1.0.
I had to manually edit my files and remove the line breaks to get spec-and-routes working again

**Comment by ronjouch** [comment]
I'm interested in this feature as well, and would have company time to work on it.

@WoH do you feel this is within reach of a new contributor? In this case I'd expect tsoa to "resolve" / "unroll" the utility types to a "dumb", "flat" Utility-less type that can then be exposed in the OpenApi definition.

→ Do tsoa/TS already have close to the necessary machinery to work with utility types and "resolve" / "unroll" them, or does this smell like a large project with sharp teeth? If you feel this is doable for a newcomer, can you offer a few rough pointers to implement it?

My use case is similar to OP's: a few functions we feed to tsoa have return types using `Omit<T>` / `Pick<T>`, and tsoa chokes on them. And so, for now, we dropped the typing ball to get tsoa to run and we sadly downgraded return types using utility functions to `any`s 😕. Of course, we'd like to fix that and have proper return types, keeping the `Omit`s / `Pick`s, without having to manually unroll / resolve them.

Example tsoa error:

```
There was a problem resolving type of 'PCDv3'.
There was a problem resolving type of 'Pick<Provider, Exclude<keyof Provider, 'foo' | 'bar' | 'baz'>>'.
There was a problem resolving type of 'Omit<Provider, 'foo' | 'bar' | 'baz'>'.
There was a problem resolving type of 'SanitizedProvider'.
Generate routes error.
 GenerateMetadataError: Unknown type: MappedType
At: /home/ronanj/conn/node_modules/mydep/dist/src-types/PCDv3/PCDv3.d.ts:16:16.
This was caused by 'bar: {
            [authType in AuthorizationType]?: PCDAuthorization;
        };'
    at TypeResolver.resolve (/home/ronanj/conn/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:356:19)
    at /home/ronanj/conn/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:131:118
    at Array.reduce (<anonymous>)
    at TypeResolver.resolve (/home/ronanj/conn/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:130:18)
    at TypeResolver.propertyFromSignature (/home/ronanj/conn/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:822:143)
    at /home/ronanj/conn/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:788:125
    at Array.map (<anonymous>)
    at TypeResolver.getModelProperties (/home/ronanj/conn/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:788:104)
    at TypeResolver.getModelReference (/home/ronanj/conn/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:659:33)
    at TypeResolver.getReferenceType (/home/ronanj/conn/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:606:38)
```

**Comment by WoH** [comment]
This is doable but the docs on Compiler APIs and the type checker are not great.
If you ask on the TS discord you'll likely get answers though.

I've given up parsing complex conditional types and just ask the type checker what it thinks it is.

Imo look at the type resolver for mapped and conditional types, try to debug your failing types and see how far you get.

I'm fine folding them into whatever you want regardless of reuse,  readability etc as long as it improves correctness.

**Comment by ronjouch** [comment]
Thanks @WoH for the details & pointers, looking into it. Zero promises made, will chime in here if I get somewhere.

**Comment by luke-lewandowski** [comment]
@ronjouch - Hey, I wonder where you have gotten with this one. We have the same issue; we refactored to remove redundant interfaces & types, and boom. TSOA won't generate routes and specs anymore.

We don't want to go back to the mess we had before.

**Comment by ronjouch** [comment]
@luke-lewandowski nothing to report on my side; the project motivating me to work on this is on hold.
