### ISSUE TITLE
Generate swagger error.  Error: Unknown type: BigIntKeyword

### ISSUE THREAD

**Issue by guhyeon** [lukeautry/tsoa#1242]
with bigint model generate swagger failed.

error message
`
There was a problem resolving type of 'member'.
Generate swagger error.
 Error: Unknown type: BigIntKeyword
At: my_projects\node_modules\.prisma\client\index.d.ts:272:272.
This was caused by 'bigint | null'
    at new GenerateMetadataError (my_projects\node_modules\@tsoa\cli\dist\metadataGeneration\exceptions.js:22:28)
    at TypeResolver.resolve (my_projects\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:334:19)
    at my_projects\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:116:95
    at Array.map (<anonymous>)
    at TypeResolver.resolve (my_projects\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:115:45)
    at my_projects\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:151:118
    at Array.reduce (<anonymous>)
    at TypeResolver.resolve (my_projects\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:150:18)
    at TypeResolver.getTypeAliasReference (my_projects\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:594:353)
    at TypeResolver.getReferenceType (my_projects\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:569:38)

`

`
/**
 * Model member
 * 
 */
export type member = {
  accountId: bigint | null
}`

generate spec
`tsoa spec`

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml

```

```ts

```

## Current Behavior

```yaml

```

```ts

```

## Possible Solution

need to support javascript bigint type.
it will be ok, convert bigint to int or number when generating swagger.

## Steps to Reproduce

1. 2. 3. 4.

## Context (Environment)
Version of the library: 
Version of NodeJS: 

- Confirm you were using yarn not npm: [x]

## Detailed Description

There was a problem resolving type of 'member'.
Generate swagger error.
 Error: Unknown type: BigIntKeyword
At: my_projects\node_modules\.prisma\client\index.d.ts:272:272.
This was caused by 'bigint | null'
    at new GenerateMetadataError (my_projects\node_modules\@tsoa\cli\dist\metadataGeneration\exceptions.js:22:28)
    at TypeResolver.resolve (my_projects\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:334:19)
    at my_projects\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:116:95
    at Array.map (<anonymous>)
    at TypeResolver.resolve (my_projects\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:115:45)
    at my_projects\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:151:118
    at Array.reduce (<anonymous>)
    at TypeResolver.resolve (my_projects\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:150:18)
    at TypeResolver.getTypeAliasReference (my_projects\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:594:353)
    at TypeResolver.getReferenceType (my_projects\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:569:38)

**Comment by guhyeon** [comment]
I stucked with same problem

**Comment by guhyeon** [comment]
solution.

`yarn add --dev  @tsoa/cli@^3.14.1 patch-package`

add resolutions in package.json
```
  "resolutions": {
    "@tsoa/cli": "^3.14.1"
  }
```
add postinstall in package.json
 ```
 "scripts": {
    "postinstall": "patch-package",
```

create patch file and directory 
patches/@tsoa+cli+3.14.1.patch
```
diff --git a/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js b/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js
index 9fa6ec3..8700f6c 100644
--- a/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js
+++ b/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js
@@ -52,7 +52,8 @@ var TypeResolver = /** @class */ (function () {
         this.context = context;
         this.referencer = referencer;
         this.attemptToResolveKindToPrimitive = function (syntaxKind) {
-            if (syntaxKind === ts.SyntaxKind.NumberKeyword) {
+            // bigint to number
+            if (syntaxKind === ts.SyntaxKind.NumberKeyword || syntaxKind === 157) {
                 return {
                     foundMatch: true,
                     resolvedType: 'number',

```

**Comment by DaveMcMartin** [comment]
Hello,

I'm having the same error, using Prisma.

`There was a problem resolving type of 'usuarios'.
Generate swagger error.
 GenerateMetadataError: Unknown type: BigIntKeyword
At: cv-experience-server/node_modules/.prisma/client/index.d.ts:336:336.
This was caused by 'id_usuario: bigint'
    at TypeResolver.resolve (cv-experience-server/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:356:19)
    at cv-experience-server/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:131:118
    at Array.reduce (<anonymous>)
    at TypeResolver.resolve (cv-experience-server/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:130:18)
    at TypeResolver.getTypeAliasReference (cv-experience-server/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:625:126)
    at TypeResolver.getReferenceType (cv-experience-server/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:594:38)
    at TypeResolver.resolve (cv-experience-server/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:389:36)
    at TypeResolver.resolve (cv-experience-server/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:374:128)
    at TypeResolver.resolve (cv-experience-server/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:379:118)
    at MethodGenerator.Generate (cv-experience-server/node_modules/@tsoa/cli/dist/metadataGeneration/methodGenerator.js:39:78)`

usuarios type definition:
`/**
 * Model usuarios
 * 
 */
export type usuarios = {
  id_usuario: bigint
  id_conta: bigint
  nome: string
  login: string
  status: string
  administrador: string
  email: string
  telefone: string | null
  id_usuario_insercao: bigint | null
  id_usuario_alteracao: bigint | null
  data_hora_insercao: Date | null
  data_hora_alteracao: Date | null
  id_pessoa: bigint | null
  id_perfil: bigint
  tipo_usuario: string
  senha: string | null
  link_imagem: string | null
}`

This model is auto generate by Prisma, I can't change it. Is there some kind of type adapter to solve this problem?
