### ISSUE TITLE
path-mapping for interface not deeply

### ISSUE THREAD

**Issue by liaojiwei666** [lukeautry/tsoa#1255]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

The path-mapping that I set up on tsoa.config.compilerOptions could mapping correctly.
```json
{
  "entryFile": "src/index.ts",
  "noImplicitAdditionalProperties": "throw-on-extras",
  "controllerPathGlobs": ["src/backyard/controller/*"],
  "spec": {
    "outputDirectory": "build/backyard",
    "specVersion": 3,
  },
  "routes": {
    "basePath": "/api/v2/backyard",
    "routesDir": "build/backyard",
    "authenticationModule": "./authentication.ts"
  },
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"],
      "@public/*": ["src/public/*"],
      "@backyard/*": ["src/backyard/*"]
    }
  }
}
```

```ts
import { Controller, Get, Route } from "tsoa";
import { queryAllListingsInOrder } from "@/src/query";
import { ListingDetailDto } from "@/src/types/listing"; <-- This path could not be found

@Route("listing")
export class ListingController extends Controller {
  @Get("")
  public async getListings(): Promise<{
    listings: Array<ListingDetailDto>;
  }> {
    const listings = await queryAllListingsInOrder({
      page: 1,
      pageSize: 6,
    }).then((res) => res.payload);
    return {
      listings,
    };
  }
}
```

## Current Behavior

The `tsoa spec-and-routes` will throw error.
```ts
Generate routes error.
 GenerateMetadataError: No declarations found for referenced type ListingDetailDto.
    at TypeResolver.getModelTypeDeclaration (/Users/liaojiwei/Desktop/funwoo/backyard-api-oas/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:755:19)
    at TypeResolver.typeArgumentsToContext (/Users/liaojiwei/Desktop/funwoo/backyard-api-oas/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:880:34)
    at TypeResolver.getReferenceType (/Users/liaojiwei/Desktop/funwoo/backyard-api-oas/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:576:14)
    at TypeResolver.resolve (/Users/liaojiwei/Desktop/funwoo/backyard-api-oas/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:389:36)
    at TypeResolver.resolve (/Users/liaojiwei/Desktop/funwoo/backyard-api-oas/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:374:128)
    at /Users/liaojiwei/Desktop/funwoo/backyard-api-oas/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:131:118
    at Array.reduce (<anonymous>)
    at TypeResolver.resolve (/Users/liaojiwei/Desktop/funwoo/backyard-api-oas/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:130:18)
    at TypeResolver.resolve (/Users/liaojiwei/Desktop/funwoo/backyard-api-oas/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:379:118)
    at MethodGenerator.Generate (/Users/liaojiwei/Desktop/funwoo/backyard-api-oas/node_modules/@tsoa/cli/dist/metadataGeneration/methodGenerator.js:39:78)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Possible Solution

The currently possible solution, but that was not good enough.

```json
{
  "entryFile": "src/index.ts",
  "noImplicitAdditionalProperties": "throw-on-extras",
  "controllerPathGlobs": ["src/backyard/controller/*"],
  "spec": {
    "outputDirectory": "build/backyard",
    "specVersion": 3,
    "securityDefinitions": {
      "FUNWOO_AUTH": {
        "type": "apiKey",
        "name": "x-funwoo-token",
        "in": "headers"
      }
    }
  },
  "routes": {
    "basePath": "/api/v2/backyard",
    "routesDir": "build/backyard",
    "authenticationModule": "./authentication.ts"
  },
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"],
      "@/src/types/*": ["src/types/*"], <-- add the deep path
      "@public/*": ["src/public/*"],
      "@backyard/*": ["src/backyard/*"]
    }
  }
}
```

## Context (Environment)

Version of the library: v4.0.0
Version of NodeJS: v16.13.0

- Confirm you were using yarn not npm: [yarn]

**Comment by douglasg14b** [comment]
mhm autoclose bot, leading to infinite google dead ends since first inception.

**Comment by ao-Barbosa** [comment]
Is there any known solution to this?

I am running into the same problem.

**Comment by WoH** [comment]
Would you like to provide a PR?

**Comment by WoH** [comment]
This is assuming you tried `**/*` and tsoa differs from tsc behaviour.

**Comment by olivergiess** [comment]
Bump this, same issue

**Comment by WoH** [comment]
Do you want to send a PR to fix this?

**Comment by RohitRox** [comment]
Ran into this issue, Same scenario. Why can't it resolve in the first place?
