### ISSUE TITLE
Nodenext module resolution support

### ISSUE THREAD

**Issue by jukefr** [lukeautry/tsoa#1272]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
When the typescript project is configured in esnext mode with nodenext modules, the routes should be generated with imports that reference `.js` files.

With these typescript options
```json
		"target": "esnext",
		"module": "esnext",
		"moduleResolution": "nodenext",
```
the imports are expected to be in the format `./somefile.js` (even if we are referencing a .ts file)

## Current Behavior

Currently I have to manually edit the generated output and append `.js` to the imported controllers.

This is not ideal as I have to commit the swagger and routes to my version control and cant simply generate at build time on CI.

It is also something that could easily be overlooked since its a manual step.

## Possible Solution

Support nodenext output generation.

## Steps to Reproduce

Use these typescript options
```json
		"target": "esnext",
		"module": "esnext",
		"moduleResolution": "nodenext",
```

## Context (Environment)

Version of the library: latest
Version of NodeJS: 16.x

- Confirm you were using yarn not npm: [x]

**Comment by jukefr** [comment]
Ok so after a bit of digging

For the documentation of the module resolution see https://www.typescriptlang.org/tsconfig#moduleResolution (I am using nodenext in this case)

I have tried passing a `compilerOptions` argument to the `tsoa.json` file by simply copy pasting my current tsconfig however I get an error 
```
Generate routes error.
 Error: Debug Failure. Unexpected moduleResolution: nodenext
    at Object.resolveModuleName (/home/user/Documents/list/node_modules/@tsoa/cli/node_modules/typescript/lib/typescript.js:43073:37)
    at loader_1 (/home/user/Documents/list/node_modules/@tsoa/cli/node_modules/typescript/lib/typescript.js:116606:117)
    at loadWithModeAwareCache (/home/user/Documents/list/node_modules/@tsoa/cli/node_modules/typescript/lib/typescript.js:116240:46)
    at actualResolveModuleNamesWorker (/home/user/Documents/list/node_modules/@tsoa/cli/node_modules/typescript/lib/typescript.js:116607:149)
    at resolveModuleNamesWorker (/home/user/Documents/list/node_modules/@tsoa/cli/node_modules/typescript/lib/typescript.js:116896:26)
    at resolveModuleNamesReusingOldState (/home/user/Documents/list/node_modules/@tsoa/cli/node_modules/typescript/lib/typescript.js:116994:24)
    at processImportedModules (/home/user/Documents/list/node_modules/@tsoa/cli/node_modules/typescript/lib/typescript.js:118504:35)
    at findSourceFileWorker (/home/user/Documents/list/node_modules/@tsoa/cli/node_modules/typescript/lib/typescript.js:118284:17)
    at findSourceFile (/home/user/Documents/list/node_modules/@tsoa/cli/node_modules/typescript/lib/typescript.js:118133:26)
    at /home/user/Documents/list/node_modules/@tsoa/cli/node_modules/typescript/lib/typescript.js:118085:85
error Command failed with exit code 1.
```

So I looked into the source of the error and found that for some reason in this case the moduleResolution seems to be mapped to 
```
export enum ModuleResolutionKind {
    Classic = 1,
    NodeJs = 2,
    Node16 = 3,
    NodeNext = 99
}
```

So I tried it out and it seems to at the very least allow passing these numbers.

However I tried with the Node16 and NodeNext values, which should produce the wanted output, but in the routes,ts the imports still do not have the `.js` extension.

**Comment by jukefr** [comment]
Ok so after alot of simming through the code I figured out that the tsoa `routes` allows for an undocumented (https://tsoa-community.github.io/reference/interfaces/extendedroutesconfig.html) property `esm` which if set to true will output the modules if the wanted import format.

So for people coming across this the config would look something like
```
	"routes": {
		"esm": true
	},
```

I don't know if these docs are autogenerated but there might be something wrong with the process.

I will close this issue for now but it might be worth opening one about documenting this property.

**Comment by falk-stefan** [comment]
@jukefr life saver :pray:

**Comment by douglasg14b** [comment]
Damn , that docs link is dead :(

**Comment by WoH** [comment]
https://tsoa-community.github.io/reference/interfaces/tsoa.RoutesConfig.html#esm
