### ISSUE TITLE
Yarn PNP Zero Install TSOA Dependencies Problem (ESM)

### ISSUE THREAD

**Issue by samuelexferri** [lukeautry/tsoa#1291]
## Sorting

- **I'm submitting a ...**

  - [X] bug report
  - [ ] feature request
  - [X] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Using NodeJS v18 with TypeScript (ESM) and Yarn v3.2.2 PNP Zero Install.

I would expect zero error related to `tsoa` package.

## Current Behavior

I'm getting two distinct error:
```
src/routes/routes.ts:4:141 - error TS2307: Cannot find module '@tsoa/runtime' or its corresponding type declarations.

4 import { Controller, ValidationService, FieldErrors, ValidateError, TsoaRoute, HttpStatusCodeLiteral, TsoaResponse, fetchMiddlewares } from '@tsoa/runtime';
                                                                                                                                              ~~~~~~~~~~~~~~~

src/routes/routes.ts:1844:25 - error TS7006: Parameter 'status' implicitly has an 'any' type.

1844         return function(status, data, headers) {
                             ~~~~~~

src/routes/routes.ts:1844:33 - error TS7006: Parameter 'data' implicitly has an 'any' type.

1844         return function(status, data, headers) {
                                     ~~~~

src/routes/routes.ts:1844:39 - error TS7006: Parameter 'headers' implicitly has an 'any' type.

1844         return function(status, data, headers) {
                                           ~~~~~~~
```
```
Error: Your application tried to access promise.any, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
Required package: promise.any (via "promise.any/package.json")
Required by: /Users/samuelexferri/GITHUB/PROJECT/dist/routes/routes.js
    at makeError (/Users/samuelexferri/GITHUB/PROJECT/.pnp.cjs:17264:34)
    at resolveToUnqualified (/Users/samuelexferri/GITHUB/PROJECT.pnp.cjs:18177:21)
    at Object.resolveToUnqualified (/Users/samuelexferri/GITHUB/PROJECT/.pnp.cjs:18327:26)
    at resolve$1 (file:///Users/samuelexferri/GITHUB/PROJECT/.pnp.loader.mjs:211:31)
    at ESMLoader.resolve (node:internal/modules/esm/loader:605:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:318:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36)
```

## Possible Solution

I was able to resolve these errors adding two dependencies:
- "@tsoa/runtime": "^4.1.0"
- "promise.any": "^2.0.4"

Is this the right way? Or maybe Yarn PNP Zero Install can't resolve the dependencies correctly?

## Steps to Reproduce

Using NodeJS v18 with TypeScript (ESM) and Yarn v3.2.2 PNP Zero Install.
Try to run a project with `"tsoa": "^4.1.1"` installed.

## Context (Environment)

Version of the library: 4.1.1
Version of NodeJS: 18

- Confirm you were using yarn not npm: [X] (Yarn v3.2.2 PNP Zero Install)

**Comment by samuelexferri** [comment]
Maybe related to #1025?
