### ISSUE TITLE
Lodash should be a dependency

### ISSUE THREAD

**Issue by jboolean** [lukeautry/tsoa#1358]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
Tsoa should include all dependencies needed by the generated runtime code.

## Current Behavior

While everything worked in development, once development dependencies were stripped out and deployed to production an error surfaced that lodash was required by the generated controller but was not a dependency.

```json
2022-12-27T15:25:31.373Z	undefined	ERROR	Uncaught Exception 	{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'lodash/map'\nRequire stack:\n- /var/task/src/api/stories/StoriesController.js\n- /var/task/tsoa-build/routes.js\n- /var/task/src/app.js\n- /var/task/appHandler.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'lodash/map'",
        "Require stack:",
        "- /var/task/src/api/stories/StoriesController.js",
        "- /var/task/tsoa-build/routes.js",
        "- /var/task/src/app.js",
        "- /var/task/appHandler.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1000:17)",
        "    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1035:21)",
        "    at async start (file:///var/runtime/index.mjs:1200:23)",
        "    at async file:///var/runtime/index.mjs:1206:1"
    ]
}

````

The tsoa-generated controller has the following code

``` javascript
const map_1 = __importDefault(require("lodash/map"));
```

This shows `npm list lodash` which demonstrates that tsoa did not declare a dependency on lodash. It may have worked in the development environment because some build and development tools declare it as a dependency. 

```
npm list lodash
fourtiesnyc-backend@1.0.0 /Users/julianboilen/Repositories/fourtiesnyc/backend
├─┬ eslint-config-jboolean@0.1.0
│ └─┬ np@7.6.2
│   ├─┬ inquirer@7.3.3
│   │ └── lodash@4.17.21 deduped
│   └─┬ listr-input@0.2.1
│     ├─┬ inquirer-autosubmit-prompt@0.2.0
│     │ └─┬ inquirer@6.5.2
│     │   └── lodash@4.17.21 deduped
│     └─┬ inquirer@7.3.3
│       └── lodash@4.17.21 deduped
├─┬ serverless-offline@11.2.1
│ └─┬ @serverless/utils@6.8.1
│   ├─┬ inquirer@8.2.5
│   │ └── lodash@4.17.21 deduped
│   └── lodash@4.17.21 deduped
├─┬ serverless-plugin-typescript@2.1.4
│ └── lodash@4.17.21
└─┬ serverless@3.23.0
  ├─┬ @serverless/dashboard-plugin@6.2.2
  │ ├─┬ @serverless/event-mocks@1.1.1
  │ │ └── lodash@4.17.21 deduped
  │ └── lodash@4.17.21 deduped
  ├─┬ json-refs@3.0.15
  │ ├─┬ graphlib@2.1.8
  │ │ └── lodash@4.17.21 deduped
  │ └── lodash@4.17.21 deduped
  └── lodash@4.17.21 deduped
```

## Possible Solution

The error was resolved by manually adding lodash as a dependency, even though I am not using it.

## Steps to Reproduce

1. Integrate tsoa into an express app.
2. Write a controller
3. Strip out any development dependencies and build the app
4. Run it

## Context (Environment)

Version of the library: 4.1.3
Version of NodeJS: 16.17.1

This app uses express 4.18.2 deployed to AWS Lambda using Serverless.

- Confirm you were using yarn not npm: [ ]

## Detailed Description

Declare a dependency on lodash.

## Breaking change?

Unsure.

**Comment by jboolean** [comment]
Nevermind, I think I actually depend on it directly. My bad.
