### ISSUE TITLE
-c option not working in 5.0.0?

### ISSUE THREAD

**Issue by aaleksandrov** [lukeautry/tsoa#1363]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```
 yarn tsoa spec -c ./tsoa-consumer.json --json
```
swagger file should be generated

## Current Behavior

```
yarn tsoa spec -c ./tsoa-consumer.json --json
yarn run v1.21.1
$ /home/alexey.aleksandrov/work/fridge-serverless-stream-ingester/node_modules/.bin/tsoa spec -c ./tsoa-consumer.json --json
[Error: ENOENT: no such file or directory, open '/home/alexey.aleksandrov/work/fridge-serverless-stream-ingester/tsoa.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/alexey.aleksandrov/work/fridge-serverless-stream-ingester/tsoa.json'
}
Generate swagger error.
 Error: Unhandled error encountered loading 'tsoa.json': ENOENT: no such file or directory, open '/home/alexey.aleksandrov/work/fridge-serverless-stream-ingester/tsoa.json'
    at getConfig (/home/alexey.aleksandrov/work/fridge-serverless-stream-ingester/node_modules/@tsoa/cli/dist/cli.js:71:19)
    at async SpecGenerator (/home/alexey.aleksandrov/work/fridge-serverless-stream-ingester/node_modules/@tsoa/cli/dist/cli.js:230:24)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Steps to Reproduce

1. Create a valid file tsoa-consumer.json
2. Run 
```
yarn tsoa spec -c ./tsoa-consumer.json --json
```

## Context (Environment)

Version of the library: 5.0.0
Version of NodeJS: v14.18.0

- Confirm you were using yarn not npm: [x]

**Comment by WoH** [comment]
Seems like maybe the yargs upgrade unintentionally broke something. Would you like to submit a PR to fix this?

**Comment by WoH** [comment]
FYI, `--configuration` is still fine
