### ISSUE TITLE
`Dynamic require of "promise.any" is not supported` when using `expressAuthentication`

### ISSUE THREAD

**Issue by keinsell** [lukeautry/tsoa#1370]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

`tosa` should return `null` as user.

```yaml

```

```ts
import * as express from 'express'
import * as jwt from 'jsonwebtoken'

export async function expressAuthentication(
	request: express.Request,
	securityName: string,
	scopes?: string[]
): Promise<null> {
	return null
}
```

## Current Behavior

`tsoa` fails by wrong build.

```yaml
server:dev: Error: Dynamic require of "promise.any" is not supported
server:dev:     at file:///Users/keinsell/Projects/neuronek/apps/server/dist/index.js:16:273
server:dev:     at file:///Users/keinsell/Projects/neuronek/apps/server/dist/index.js:16:13985
server:dev:     at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

```ts

```

## Steps to Reproduce

1. 2. 3. 4.

## Context (Environment)

Version of the library: 5.0.0
Version of NodeJS: 19.4.0

- Confirm you were using yarn not npm: [x]

**Comment by keinsell** [comment]
Nevermind, solved by adding `"esm": true` to my `tsoa.json`.

```
{
	"entryFile": "src/index.ts",
	"noImplicitAdditionalProperties": "throw-on-extras",
	"controllerPathGlobs": ["**/*.controller.ts", "*/**/*.controller.ts"],
	"spec": {
		"outputDirectory": "dist",
		"specVersion": 3,
		"securityDefinitions": {
			"Bearer": {
				"type": "http",
				"scheme": "bearer",
				"bearerFormat": "JWT"
			}
		},
		"security": [{ "Bearer": [] }]
	},
	"routes": {
		"basePath": "/",
		"entryFile": "src/index.ts",
		"routesDir": "dist",
		"authenticationModule": "src/shared/infrastructure/authorization/auth.ts",
		"iocModule": "src/shared/infrastructure/ioc/container.ts",
		"esm": true
	}
}
```
