### ISSUE TITLE
CLI: unable to use --configuration option

### ISSUE THREAD

**Issue by pquerner** [lukeautry/tsoa#1427]
Hello!

I found https://tsoa-community.github.io/docs/generating.html but I am unable this code. It fails with:

```
Error: Missing entryFile and controllerPathGlobs: Configuration must contain an entry point file or controller path globals.
    at validateRoutesConfig (/x/node_modules/@tsoa/cli/dist/cli.js:148:15)
    at routeGenerator (/x/node_modules/@tsoa/cli/dist/cli.js:260:36)

```

`tsoa.ts`
```
import {
    generateRoutes,
    generateSpec,
    ExtendedRoutesConfig,
    ExtendedSpecConfig,
} from "tsoa";

(async () => {
    const specOptions: ExtendedSpecConfig = {
        basePath: "/",
        noImplicitAdditionalProperties: "throw-on-extras",
        entryFile: "./src/server.ts",
        specVersion: 3,
        outputDirectory: "./swagger",
        controllerPathGlobs: ["./src/**/*Controller.ts"],
    };

    const routeOptions: ExtendedRoutesConfig = {
        noImplicitAdditionalProperties: "throw-on-extras",
        basePath: "/",
        entryFile: "./src/server.ts",
        routesDir: "./src/routes",
    };

    await generateSpec(specOptions);

    await generateRoutes(routeOptions);
})();

```

`package.json`
```
"tsoa": "rimraf tsoa.js && tsc --allowJs --resolveJsonModule tsoa.ts && tsoa routes --configuration tsoa.js && tsoa spec --configuration tsoa.js",
```

Old tsoa.json for reference

```
{
    "entryFile": "src/server.ts",
    "noImplicitAdditionalProperties": "throw-on-extras",
    "controllerPathGlobs": [
        "src/**/*Controller.ts"
    ],
    "spec": {
        "outputDirectory": "swagger",
        "specVersion": 3,
        "securityDefinitions": {
            "api_key": {
              "type": "apiKey",
              "name": "x-api-key",
              "in": "header"
            }
          }
    },
    "routes": {
        "routesDir": "src/routes",
        "authenticationModule": "./src/middlewares/authentication.ts"
    }
}

```

Is this how it should be used?
(I have seen #868 and #1354 use it somewhat the same)

Reason I want to switch to the `tsoa.js` (or .ts) is because of #1426:
I want to change `controllerPathGlobs` on some condition (or set each controller there, without using globs)

**Comment by pquerner** [comment]
This kinda works, but it produces a slighty different swagger.json than before.

```
import {ExtendedRoutesConfig, ExtendedSpecConfig} from "tsoa";

const {
    generateRoutes,
    generateSpec,
    ExtendedRoutesConfig,
    ExtendedSpecConfig,
} = require("tsoa");

const specOptions: ExtendedSpecConfig = {
    basePath: "/",
    noImplicitAdditionalProperties: "throw-on-extras",
    entryFile: "src/server.ts",
    specVersion: 3,
    outputDirectory: "swagger",
    spec: {
        rootSecurity: '',
        outputDirectory: 'swagger',
    },
    controllerPathGlobs: ["src/**/*Controller.ts"],
};

const routeOptions = {
    noImplicitAdditionalProperties: "throw-on-extras",
    controllerPathGlobs: ["src/**/*Controller.ts"],
    basePath: "/",
    entryFile: "src/server.ts",
    routesDir: "src/routes",
    routes: {
        routesDir: "src/routes",
    },
    authenticationModule: "./src/middlewares/authentication.ts"
};

const config = {
    ...specOptions,
    ...routeOptions,
};

generateSpec(specOptions).catch((error:string) => {
    console.error("Error generating spec:", error);
});

generateRoutes(routeOptions).catch((error:string) => {
    console.error("Error generating routes:", error);
});

module.exports = config;

```

and I cannot use `ExtendedRoutesConfig` since I dont use the interface correctly. But if I dont have the object like that, loads of things break in `node_modules/@tsoa/cli/dist/cli.js`

like
```
const validateSpecConfig = async (config) => {
    if (!config.spec) {
        throw new Error('Missing spec: configuration must contain spec. Spec used to be called swagger in previous versions of tsoa.');
    }
    if (!config.spec.outputDirectory) {
        throw new Error('Missing outputDirectory: configuration must contain output directory.');
    }
    if (!config.entryFile && (!config.controllerPathGlobs || !config.controllerPathGlobs.length)) {
        throw new Error('Missing entryFile and controllerPathGlobs: Configuration must contain an entry point file or controller path globals.');
    }
    if (!!config.entryFile && !(await (0, fs_1.fsExists)(config.entryFile))) {
        throw new Error(`EntryFile not found: ${config.entryFile} - please check your tsoa config.`);
    }
//...
```

Is this the intended way?
