### ISSUE TITLE
Type Aliases not working when imported from ambient module

### ISSUE THREAD

**Issue by alexng353** [lukeautry/tsoa#1653]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I expect that in the following code snippets, tsoa will properly resolve the imports & types, generating the correct openapi schema on output.

```ts
// types.ts
/**
 * Stringified UUIDv4.
 * See [RFC 4112](https://tools.ietf.org/html/rfc4122)
 * @pattern [0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}
 * @format uuid
 */
export type UUID = string;
```

```ts
// thing.controller.ts
import type { UUID } from "types.ts";

@Route("/api/v1/user/")
export class UserController extends Controller {
  @Get("/")
  @Security("jwt")
  async getUsers(
    @Query("userIds") userIds: UUID[],
  ): Promise<NonSensitiveUser[]> {
    const users = await db
      .select(defaultUserSelection)
      .from(Users)
      .where(inArray(Users.id, userIds));

    return users;
  }
}
```
## Current Behavior

Tsoa errors while attempting to build and generate swagger for this code.

<img width="1479" alt="image" src="https://github.com/user-attachments/assets/51fcd1cc-9161-4afd-bba7-ee0b85555296">

<details>
<summary>Full Error Message (plaintext)</summary>
<br>

```bash
killing previous process
Generate routes error.
 GenerateMetadataError: No declarations found for referenced type UUID.
 in 'UserController.getUsers'
    at /Users/alex/code/edubeyond/mono/2024-07/27-tsoa-postgres/node_modules/.pnpm/@tsoa+cli@6.4.0/node_modules/@tsoa/cli/dist/metadataGeneration/methodGenerator.js:104:23
    at Array.map (<anonymous>)
    at MethodGenerator.buildParameters (/Users/alex/code/edubeyond/mono/2024-07/27-tsoa-postgres/node_modules/.pnpm/@tsoa+cli@6.4.0/node_modules/@tsoa/cli/dist/metadataGeneration/methodGenerator.js:96:14)
    at MethodGenerator.Generate (/Users/alex/code/edubeyond/mono/2024-07/27-tsoa-postgres/node_modules/.pnpm/@tsoa+cli@6.4.0/node_modules/@tsoa/cli/dist/metadataGeneration/methodGenerator.js:66:33)
    at /Users/alex/code/edubeyond/mono/2024-07/27-tsoa-postgres/node_modules/.pnpm/@tsoa+cli@6.4.0/node_modules/@tsoa/cli/dist/metadataGeneration/controllerGenerator.js:46:41
    at Array.map (<anonymous>)
    at ControllerGenerator.buildMethods (/Users/alex/code/edubeyond/mono/2024-07/27-tsoa-postgres/node_modules/.pnpm/@tsoa+cli@6.4.0/node_modules/@tsoa/cli/dist/metadataGeneration/controllerGenerator.js:46:14)
    at ControllerGenerator.Generate (/Users/alex/code/edubeyond/mono/2024-07/27-tsoa-postgres/node_modules/.pnpm/@tsoa+cli@6.4.0/node_modules/@tsoa/cli/dist/metadataGeneration/controllerGenerator.js:35:27)
    at /Users/alex/code/edubeyond/mono/2024-07/27-tsoa-postgres/node_modules/.pnpm/@tsoa+cli@6.4.0/node_modules/@tsoa/cli/dist/metadataGeneration/metadataGenerator.js:210:41
    at Array.map (<anonymous>)
error: "tsoa" exited with code 1
Failed to reload tsoa
```

</details>

## Steps to Reproduce

You can see this error by copying the provided code blocks.

## Context (Environment)

Version of the library: `^6.4.0`
Version of NodeJS: `v20.15.0`

- Confirm you were using yarn not npm: [x]

## Detailed Description

I am directly copying code from [the docs](https://tsoa-community.github.io/docs/descriptions.html), so I expect this to work properly.

**Comment by victor-floor** [comment]
I'm facing the same issue with an interface defined in a different file and used as the response.

**Comment by Enquier** [comment]
Same here.

**Comment by WoH** [comment]
Please add them to the program file. See TSC with the list files switch

**Comment by alexng353** [comment]
bump

**Comment by nullbytesoftware** [comment]
same

**Comment by nullbytesoftware** [comment]
copying tsconfig.json -> compilerOptions.paths to `tsoa.json` fixes the issue for me:

```
"compilerOptions": {
    "baseUrl": ".",
    "paths": { "@/*": ["src/*"], "~/*": ["./*"] }
  }
```
