### ISSUE TITLE
Feature request: Support "exports" and "imports" in package.json

### ISSUE THREAD

**Issue by JavaScriptBach** [lukeautry/tsoa#1659]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
I work in a Typescript mono-repo, where all our imports are bare imports instead of relative imports. We define `exports` and `imports` in package.json to control what each package exports. It would be great if tsoa knew how to resolve these imports.

See https://github.com/JavaScriptBach/tsoa-repro for an example.

## Current Behavior
tsoa does not know how to resolve these imports:

```
Generate routes error.
 GenerateMetadataError: No declarations found for referenced type User.
    at TypeResolver.getModelTypeDeclarations (/Users/philliphuang/tsoa-repro/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:871:62)
    at TypeResolver.calcRefTypeName (/Users/philliphuang/tsoa-repro/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:536:39)
    at TypeResolver.calcTypeReferenceTypeName (/Users/philliphuang/tsoa-repro/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:712:34)
    at TypeResolver.getReferenceType (/Users/philliphuang/tsoa-repro/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:721:35)
    at TypeResolver.resolveTypeReferenceNode (/Users/philliphuang/tsoa-repro/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:468:21)
    at TypeResolver.resolve (/Users/philliphuang/tsoa-repro/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:293:21)
    at TypeResolver.resolveTypeReferenceNode (/Users/philliphuang/tsoa-repro/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:458:93)
    at TypeResolver.resolve (/Users/philliphuang/tsoa-repro/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:293:21)
    at MethodGenerator.Generate (/Users/philliphuang/tsoa-repro/node_modules/@tsoa/cli/dist/metadataGeneration/methodGenerator.js:62:78)
    at /Users/philliphuang/tsoa-repro/node_modules/@tsoa/cli/dist/metadataGeneration/controllerGenerator.js:46:41
error Command failed with exit code 1.

```

## Steps to Reproduce

https://github.com/JavaScriptBach/tsoa-repro

## Context (Environment)

Version of the library: 6.4.0
Version of NodeJS: 18.14.0

- Confirm you were using yarn not npm: [x]

## Detailed Description
It would be nice if tsoa understand how to resolve these fields:
- https://nodejs.org/api/packages.html#exports
- https://nodejs.org/api/packages.html#subpath-imports
- https://nodejs.org/api/packages.html#conditional-exports

These fields have been around since ~Node 12 and all major tooling (e.g. Typescript, bundlers) know how to understand them.

Currently, I can hack around this issue by passing custom tsconfig options to tsoa. But this is not ideal because I have to define the import paths in 2 different locations (package.json and in tsoa).

## Breaking change?
This could break generation depending on what users have defined in their `exports` or `imports` in package.json.

**Comment by JavaScriptBach** [comment]
Bump

**Comment by JavaScriptBach** [comment]
Bump

**Comment by JavaScriptBach** [comment]
Why does tsc matter here? The rules to resolve the imports are defined in package.json.

**Comment by JavaScriptBach** [comment]
Did this get implemented? If so, which release contains it?

**Comment by kibiz0r** [comment]
I ran into this today.

@JavaScriptBach You mentioned working around it by duplicating tsconfig options, can you show a snippet of what option you're using to get past this?

@WoH Can we reopen this issue?
