### ISSUE TITLE
Using Prisma with TSOA

### ISSUE THREAD

**Issue by wolffsteinn** [lukeautry/tsoa#1704]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ x ] feature request
  - [ ] support request

- I confirm that I
  - [ x ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit
  > Note: There is a similar issue, but it was not natively fixed on tsoa itself but used a third-party package. (https://github.com/lukeautry/tsoa/issues/1481)

## Expected Behavior

```ts
import { CoreDatabaseService } from './databaseService';
import type { admin_roles } from '@prisma/client; // ideally reads the type from prisma itself

export class CoreService {
  constructor(private coreDatabaseService: CoreDatabaseService) {}

  async getAdminRoles(): Promise<admin_roles[] | null> {
    try {
      const roles = await this.coreDatabaseService.admin_roles.findMany();
      console.log(roles);
      return roles;
    } catch (error) {
      console.log(error);
      return null;
    }
  }
}
```

## Current Behavior

```ts
import { CoreDatabaseService } from './databaseService';

// i have to recreate the types in an interface, which might be out of sync from prisma if multiple people are working on it
interface admin_roles {
  id: number,
  role_name: string
}

export class CoreService {
  constructor(private coreDatabaseService: CoreDatabaseService) {}

  async getAdminRoles(): Promise<admin_roles[] | null> {
    try {
      const roles = await this.coreDatabaseService.admin_roles.findMany();
      console.log(roles);
      return roles;
    } catch (error) {
      console.log(error);
      return null;
    }
  }
}
```

An error is shown stating that tsoa is unable to reference the type `admin_roles` from prisma client 
```yaml
Generate routes error.
 GenerateMetadataError: No declarations found for referenced type admin_roles.
    at TypeResolver.getModelTypeDeclarations (/Users/annabel/Work/rapidzpay-tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:871:62)
    at TypeResolver.calcRefTypeName (/Users/annabel/Work/rapidzpay-tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:536:39)
    at TypeResolver.calcTypeReferenceTypeName (/Users/annabel/Work/rapidzpay-tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:712:34)
    at TypeResolver.getReferenceType (/Users/annabel/Work/rapidzpay-tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:721:35)
    at TypeResolver.resolveTypeReferenceNode (/Users/annabel/Work/rapidzpay-tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:468:21)
    at TypeResolver.resolve (/Users/annabel/Work/rapidzpay-tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:293:21)
    at TypeResolver.resolve (/Users/annabel/Work/rapidzpay-tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:81:119)
    at TypeResolver.resolveTypeReferenceNode (/Users/annabel/Work/rapidzpay-tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:458:93)
    at TypeResolver.resolve (/Users/annabel/Work/rapidzpay-tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:293:21)
    at MethodGenerator.Generate (/Users/annabel/Work/rapidzpay-tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/methodGenerator.js:62:78)
```

## Possible Solution

allow tsoa's typeresolver to be able to read the prisma types that have been generated in the schema?

## Steps to Reproduce

1. 2. 3. 4.

## Context (Environment)

Version of the library: 6.5.0
Version of NodeJS: 20.17.0

> Note: i was using npm for this

**Comment by WoH** [comment]
Is the declaration included in your tsc config?

`yarn tsc --listFilesOnly`

**Comment by wolffsteinn** [comment]
sorry, im not sure if these are the stuff that you are looking for? i just selected those that seem to be most likely the ones that we require for this discussion!

``` ts
/Users/annabel/Work/node_modules/typescript/lib/lib.decorators.d.ts
/Users/annabel/Work/node_modules/typescript/lib/lib.decorators.legacy.d.ts
/Users/annabel/Work/node_modules/@tsoa/runtime/dist/decorators/deprecated.d.ts
/Users/annabel/Work/node_modules/@tsoa/runtime/dist/decorators/example.d.ts
/Users/annabel/Work/node_modules/@tsoa/runtime/dist/decorators/parameter.d.ts
/Users/annabel/Work/node_modules/@tsoa/runtime/dist/decorators/methods.d.ts
/Users/annabel/Work/node_modules/@tsoa/runtime/dist/decorators/tags.d.ts
/Users/annabel/Work/node_modules/@tsoa/runtime/dist/decorators/operationid.d.ts
/Users/annabel/Work/node_modules/@tsoa/runtime/dist/decorators/route.d.ts
/Users/annabel/Work/node_modules/@tsoa/runtime/dist/decorators/security.d.ts
/Users/annabel/Work/node_modules/@tsoa/runtime/dist/decorators/extension.d.ts
/Users/annabel/Work/node_modules/@tsoa/runtime/dist/decorators/middlewares.d.ts
/Users/annabel/Work/node_modules/@tsoa/runtime/dist/decorators/response.d.ts
```

**Comment by WoH** [comment]
As the error says, the file where the declaration is is probably not part of your files. 
The tsoa ones should not matter, but the file where admin_roles is declared should be

**Comment by wolffsteinn** [comment]
so its probably not a `bigint` issue? and in the `--listFilesOnly` i should be seeing files related to admin_roles that is being declared?

sorry im not too proficient in this

**Comment by WoH** [comment]
Rather tsoa does not know how you'll serialize it in JSON

**Comment by nvti** [comment]
> Rather tsoa does not know how you'll serialize it in JSON

So how do we define serialize for bigint?

**Comment by carlosalaniz** [comment]
bump bump

**Comment by WoH** [comment]
> > Rather tsoa does not know how you'll serialize it in JSON
> 
> So how do we define serialize for bigint?

Yolo it into a number, toString it, or prepend it with some magic prefix. None if that tsoa will spec out, but you should probably not have type bigint in an interface that you expose via json.
