### ISSUE TITLE
Unable to resolve Return types from different files.

### ISSUE THREAD

**Issue by Enquier** [lukeautry/tsoa#1735]
## Sorting

- **I'm submitting a ...**

  - [ X] bug report
  - [ ] feature request
  - [X ] support request

- I confirm that I
  - [X ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I have a controller which returns a type that is defined in another file, however TSOA fails to find it  during generation. Not sure if this is a relative path issue?

```yaml

```

```ts

```

## Current Behavior

```ts
import { IType } from 'folder/file';

@Post('{path}')
createOrUpdateType(@Path() path
    ): Promise<IElementsResponse> {
...stufff
}
```

## Steps to Reproduce

run tsoa spec-and-routes with some thing similar to above:
```
Generate routes error.
 GenerateMetadataError: No declarations found for referenced type IElementsResponse.
    at TypeResolver.getModelTypeDeclarations (C:\Users\119481\git\ddp-api-server\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:871:62)
    at TypeResolver.calcRefTypeName (C:\Users\119481\git\ddp-api-server\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:536:39)
    at TypeResolver.calcTypeReferenceTypeName (C:\Users\119481\git\ddp-api-server\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:712:34)
    at TypeResolver.getReferenceType (C:\Users\119481\git\ddp-api-server\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:721:35)
    at TypeResolver.resolveTypeReferenceNode (C:\Users\119481\git\ddp-api-server\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:468:21)
    at TypeResolver.resolve (C:\Users\119481\git\ddp-api-server\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:293:21)
    at TypeResolver.resolveTypeReferenceNode (C:\Users\119481\git\ddp-api-server\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:458:93)
    at TypeResolver.resolve (C:\Users\119481\git\ddp-api-server\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:293:21)
    at MethodGenerator.Generate (C:\Users\119481\git\ddp-api-server\node_modules\@tsoa\cli\dist\metadataGeneration\methodGenerator.js:62:78)
    at C:\Users\119481\git\ddp-api-server\node_modules\@tsoa\cli\dist\metadataGeneration\controllerGenerator.js:46:41
```
1. 2. 3. 4.

## Context (Environment)

Version of the library: "^6.5.1"
Version of NodeJS:  "22.x"

- Confirm you were using yarn not npm: [X ]

**Comment by Enquier** [comment]
Similar to the closed (stale) issue #1653 ?

**Comment by Enquier** [comment]
I did a little more testing and it seems as though if I put in a full relative path it works: "eg ../../path/to/file as opposed to path/to/file

**Comment by Enquier** [comment]
Added some config to compiler options... didn't realize TSOA wasn't taking from the local tsconfig (my bad)

**Comment by ThalysSilva** [comment]
what compile you add ?
