### ISSUE TITLE
Problems running sample repository.

### ISSUE THREAD

**Issue by eduardowickertg** [lukeautry/tsoa#177]
I am trying to run the sample repo with no success.

What did I do: cloned the sample repo, npm i and npm start.
What I am getting:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@4.2.0
3 info using node@v7.10.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle tsoa-example@0.0.1~prebuild: tsoa-example@0.0.1
6 silly lifecycle tsoa-example@0.0.1~prebuild: no script for prebuild, continuing
7 info lifecycle tsoa-example@0.0.1~build: tsoa-example@0.0.1
8 verbose lifecycle tsoa-example@0.0.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle tsoa-example@0.0.1~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/eduardo/VS Code/tsoa-example/node_modules/.bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/home/eduardo/VS Code/tsoa-example/node_modules$
10 verbose lifecycle tsoa-example@0.0.1~build: CWD: /home/eduardo/VS Code/tsoa-example
11 silly lifecycle tsoa-example@0.0.1~build: Args: [ '-c',
11 silly lifecycle   'npm run clean && npm run lint && npm run swagger-gen && npm run routes-gen && tsc && npm run copy-swagger-ui' ]
12 silly lifecycle tsoa-example@0.0.1~build: Returned: code: 2  signal: null
13 info lifecycle tsoa-example@0.0.1~build: Failed to exec build script
14 verbose stack Error: tsoa-example@0.0.1 build: `npm run clean && npm run lint && npm run swagger-gen && npm run routes-gen && tsc && npm run copy-swagger-ui`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid tsoa-example@0.0.1
16 verbose cwd /home/eduardo/VS Code/tsoa-example
17 error Linux 4.10.0-30-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
19 error node v7.10.1
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 2
23 error tsoa-example@0.0.1 build: `npm run clean && npm run lint && npm run swagger-gen && npm run routes-gen && tsc && npm run copy-swagger-ui`
23 error Exit status 2
24 error Failed at the tsoa-example@0.0.1 build script 'npm run clean && npm run lint && npm run swagger-gen && npm run routes-gen && tsc && npm run copy-swagger-ui'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the tsoa-example package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     npm run clean && npm run lint && npm run swagger-gen && npm run routes-gen && tsc && npm run copy-swagger-ui
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs tsoa-example
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls tsoa-example
24 error There is likely additional logging output above.
25 verbose exit [ 2, true ]

```

**Comment by dgreene1** [comment]
I am assuming the mistake is that you didn’t install node modules by running `yarn` first. I could try to help you diagnose your issue, but I think it makes sense to close the issue since (a) this is a very old issue and (b) I just started as a maintainer on tsoa. If you or anyone else has issues, feel free to open a new PR with reproduction steps, the outcome, and desired outcomes.
