### ISSUE TITLE
Importing module as variable fails swagger file generation

### ISSUE THREAD

**Issue by jeremyoverman** [lukeautry/tsoa#195]
Given a module like so:

```javascript
// Model.ts

export interface IInstance {
    id: integer;
    name: string;
    display: string;
}
```

Imported into a controller:

```javascript
// Controller.ts

import { Get, Route } from 'tsoa';
import * as Model from './Model';

@Route('myroute')
export class Controller {
    @Get()
    get(): Model.IInstance {
        return {
            id: 1,
            name: 'name',
            display: 'display'
        }
    }
}
```

I get the error `There was a problem resolving type of 'Model.IInstance'.` It seems like tsoa isn't able to determine modules loaded using the `import * as name from 'module'` syntax?

The more detailed error is as follows:

```
Error: There was a problem resolving type of 'PackageModels.RawPackageInstance'.
Generate swagger error.
 Error: No matching module declarations found for PackageModels.
    at new GenerateMetadataError (c:\git\biddle-tsoa\node_modules\tsoa\dist\metadataGeneration\exceptions.js:17:28)
    at _loop_1 (c:\git\biddle-tsoa\node_modules\tsoa\dist\metadataGeneration\resolveType.js:387:19)
    at resolveModelTypeScope (c:\git\biddle-tsoa\node_modules\tsoa\dist\metadataGeneration\resolveType.js:400:9)
    at getModelTypeDeclaration (c:\git\biddle-tsoa\node_modules\tsoa\dist\metadataGeneration\resolveType.js:406:22)
    at getReferenceType (c:\git\biddle-tsoa\node_modules\tsoa\dist\metadataGeneration\resolveType.js:280:25)
    at resolveType (c:\git\biddle-tsoa\node_modules\tsoa\dist\metadataGeneration\resolveType.js:95:25)
    at resolveType (c:\git\biddle-tsoa\node_modules\tsoa\dist\metadataGeneration\resolveType.js:26:26)
    at Object.resolveType (c:\git\biddle-tsoa\node_modules\tsoa\dist\metadataGeneration\resolveType.js:73:20)
    at MethodGenerator.Generate (c:\git\biddle-tsoa\node_modules\tsoa\dist\metadataGeneration\methodGenerator.js:30:34)
    at c:\git\biddle-tsoa\node_modules\tsoa\dist\metadataGeneration\controllerGenerator.js:38:58

    at ChildProcess.child_process.spawn.on.code (c:\git\biddle-tsoa\gulpfile.js:21:24)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by jeremyoverman** [comment]
Diggging in a bit more, it looks like the `import * as name from './module'` `SyntaxKind` comes back as `ImportDeclaration` (239) instead of `ModuleDeclaration` in `resolveType.ts`, `resolveModelTypeScope`. This is making it filter this import out of `moduleDeclarations`. I'm not sure how big of a difference being an `ImportDeclaration` has over being a `ModuleDeclaration` as them seem at least somewhat functionally similar from an end user perspective, though deriving the interface names from that may be difficult.

**Comment by jpramondon** [comment]
Hi @jeremyoverman 

Could you please be a little more explicit on how you solved this issue. After months using tsoa, I'm facing the "There was a problem resolving type of ..." issue as well on a brand new project.
I tried both the `import * as name from` import notation and the explicit `import {myInterface} from`, but none coudl solve the problem.

Thanks for your help !

**Comment by dgreene1** [comment]
I added a readme explanation for this error: https://github.com/lukeautry/tsoa/blob/41dcf54ec2bfac4a301328f9a602718e4b2e3674/ExternalInterfacesExplanation.MD

Please see that for more information.
