### ISSUE TITLE
TypeScript 2.9.1 breaks tsoa with getTypeAtLocation TypeError

### ISSUE THREAD

**Issue by ronjouch** [lukeautry/tsoa#230]
TypeScript 2.9.1 breaks tsoa tests (and my tsoa build). See log below.

- Fixing TypeScript at 2.7.2 (as specified by package.json)
- Fixing TypeScript at 2.8.4 also fixes the issue (see PR https://github.com/lukeautry/tsoa/pull/229).

→ Problem started happening with 2.9.1, released on 2018-05-31

```sh
 ~/tsoa (master) node --version
v8.11.2

 ~/tsoa (master) npm --version
6.1.0

 ~/tsoa (master) npm test

> tsoa@2.1.4 pretest /home/ronjouch/tsoa
> cross-env NODE_ENV=test npm run build && npm run swagger-gen && cross-env NODE_ENV=test npm run routes-gen && cross-env NODE_ENV=test npm run routes-gen:hapi && cross-env NODE_ENV=test npm run routes-gen:koa && cross-env NODE_ENV=test npm run routes-gen:custom && cross-env NODE_ENV=test npm run routes-gen:inversify && npm run lint                                              

> tsoa@2.1.4 build /home/ronjouch/tsoa
> npm run clean && npm run tsc && npm run copy-templates && npm run copy-types                                                

> tsoa@2.1.4 clean /home/ronjouch/tsoa
> rimraf dist && rimraf tests/fixtures/*/routes.ts

> tsoa@2.1.4 tsc /home/ronjouch/tsoa
> tsc

> tsoa@2.1.4 copy-templates /home/ronjouch/tsoa
> copyfiles -u 1 ./src/routeGeneration/templates/**/* ./dist

> tsoa@2.1.4 copy-types /home/ronjouch/tsoa
> copyfiles -u 1 ./src/*.d.ts ./dist

> tsoa@2.1.4 swagger-gen /home/ronjouch/tsoa
> node ./dist/cli.js swagger

There was a problem resolving type of 'TestModel'.
Generate swagger error.
 TypeError: Cannot read property 'getTypeAtLocation' of undefined                                                             
    at /home/ronjouch/tsoa/node_modules/typescript/lib/typescript.js:106674:41                                            
    at Object.firstDefined (/home/ronjouch/tsoa/node_modules/typescript/lib/typescript.js:1807:26)                        
    at findInheritedJSDocComments (/home/ronjouch/tsoa/node_modules/typescript/lib/typescript.js:106673:19)               
    at getDocumentationComment (/home/ronjouch/tsoa/node_modules/typescript/lib/typescript.js:106656:37)                  
    at SymbolObject.getDocumentationComment (/home/ronjouch/tsoa/node_modules/typescript/lib/typescript.js:106505:45)     
    at getNodeDescription (/home/ronjouch/tsoa/dist/metadataGeneration/resolveType.js:622:27)                             
    at /home/ronjouch/tsoa/dist/metadataGeneration/resolveType.js:493:30                                                  
    at Array.map (<anonymous>)
    at getModelProperties (/home/ronjouch/tsoa/dist/metadataGeneration/resolveType.js:462:14)                             
    at getReferenceType (/home/ronjouch/tsoa/dist/metadataGeneration/resolveType.js:281:26)                               
```

**Comment by lukeautry** [comment]
Merged and published.
