### ISSUE TITLE
Error: Multiple matching enum found for enum InvoiceType; please make enum names unique.

### ISSUE THREAD

**Issue by gitowiec** [lukeautry/tsoa#328]
I tried method from the readme.md to add jsdoc to every type I have duplicated but it did not help (https://github.com/lukeautry/tsoa#dealing-with-duplicate-model-names)
Server uses tsoa 2.1.8, which I did upgrade to the latest but error is still available with 2.3.8.
My server has types that are duplicated outside of it in a package that is a email template - it has to have that types to know documents shape. Everything is put in a monorepo (packages/* sub-directories) 
I don't want to change names of types - is there better solution?

<pre>
There was a problem resolving type of 'InvoiceType'.
There was a problem resolving type of 'InvoicePageableRequestWithFilters'.
Generate swagger error.
 Error: Multiple matching enum found for enum InvoiceType; please make enum names unique. 
 in 'InvoicesController.getInvoices'
    at new GenerateMetadataError (/home/user/workspace/secret-project/packages/web-server/node_modules/tsoa/dist/metadataGeneration/exceptions.js:20:28)
    at /home/user/workspace/secret-project/packages/web-server/node_modules/tsoa/dist/metadataGeneration/methodGenerator.js:60:23
    at Array.map (<anonymous>)
    at MethodGenerator.buildParameters (/home/user/workspace/secret-project/packages/web-server/node_modules/tsoa/dist/metadataGeneration/methodGenerator.js:53:47)
    at MethodGenerator.Generate (/home/user/workspace/secret-project/packages/web-server/node_modules/tsoa/dist/metadataGeneration/methodGenerator.js:42:30)
    at /home/user/workspace/secret-project/packages/web-server/node_modules/tsoa/dist/metadataGeneration/controllerGenerator.js:40:58
    at Array.map (<anonymous>)
    at ControllerGenerator.buildMethods (/home/user/workspace/secret-project/packages/web-server/node_modules/tsoa/dist/metadataGeneration/controllerGenerator.js:40:14)
    at ControllerGenerator.Generate (/home/user/workspace/secret-project/packages/web-server/node_modules/tsoa/dist/metadataGeneration/controllerGenerator.js:29:27)
    at /home/user/workspace/secret-project/packages/web-server/node_modules/tsoa/dist/metadataGeneration/metadataGenerator.js:59:58
</pre>
----
Edit: I also tried this in tsoa.json without luck:
<pre>
    "ignore": [
        "**/node_modules/**"
    ]
</pre>

**Comment by softmarshmallow** [comment]
any updates?

**Comment by WoH** [comment]
I believe this should be fine in the beta releases for v3. If not, feel free to remind me to take a look.

**Comment by joantune** [comment]
@WoH  - I had the same error using:
```    "tsoa": "^3.0.4",```
