### ISSUE TITLE
Cannot run tsoa when installed globally

### ISSUE THREAD

**Issue by danzel** [lukeautry/tsoa#4]
```
npm install -g tsoa
tsoa --help
module.js:442
    throw err;
    ^

Error: Cannot find module 'C:\Users\dave\AppData\Roaming\npm/package.json'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at getPackageJsonValue (C:\Users\dave\AppData\Roaming\npm\node_modules\tsoa\dist\cli.js:107:25)
    at Object.<anonymous> (C:\Users\dave\AppData\Roaming\npm\node_modules\tsoa\dist\cli.js:33:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```
Doesn't work.

vs

```
npm install tsoa
node ./node_modules/tsoa/dist/cli.js --help
Usage: node_modules\tsoa\dist\cli.js <command> [options]

Commands:
  swagger  Generate swagger spec
  routes   Generate routes

Options:
  --help, -h  Show help                                                [boolean]
```
Works.

**Comment by danzel** [comment]
I'm on windows BTW.

**Comment by lukeautry** [comment]
I think there's a straightforward way to make this work for global
installs, but you lose some of the benefit of having it installed locally;
when you generate a swagger spec, some default values for the spec are
inferred from package.json.

That said it shouldn't blow up like this and I know why it's happening;
will put out a fix later today most likely.

**Comment by lukeautry** [comment]
@danzel This is now be fixed [in 0.0.40](https://github.com/lukeautry/tsoa/commit/71e0162ca4000d5fc698696f16d67ac30497aeaa)

**Comment by danzel** [comment]
Thanks!
Maybe it could check the PWD that the command was ran from? Then it could still find the local package.json.

**Comment by lukeautry** [comment]
I think that's a pretty good idea, I'll most likely implement that.
