### ISSUE TITLE
Model @example json cant have @ inside (like email)

### ISSUE THREAD

**Issue by sittingbool** [lukeautry/tsoa#570]
If I put an example string that contains an @ the generation fails

## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
I can use an @ in a string in my example JSON inside the header doc of my model

```ts
/**
 * This is a newsletter subscription
 * @tsoaModel
 * @example
 * {
 *   "id": "ajfhwoiur83",
 *   "email": "test@domain.net",
 *   "acceptedPrivacy": "2018-06-25T15:45:00Z"
 * }
 */
export class NewsletterModel {
    id: string;
    // email of the user, must be a valid email
    email: string;
    acceptedPrivacy: Date;
}
```

## Current Behavior
JSON parse error

```
There was a problem resolving type of 'NewsletterModel'.
Generate routes error.
 SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at TypeResolver.getNodeExample (/Users/.../Developer/.../checkout/tests/swagger-ts-test/node_modules/tsoa/dist/metadataGeneration/typeResolver.js:864:25)
    at TypeResolver.getReferenceTypeOrEnumType (/Users/.../Developer/.../checkout/tests/swagger-ts-test/node_modules/tsoa/dist/metadataGeneration/typeResolver.js:460:32)
    at TypeResolver.resolve (/Users/.../Developer/.../checkout/tests/swagger-ts-test/node_modules/tsoa/dist/metadataGeneration/typeResolver.js:228:40)
    at TypeResolver.resolve (/Users/.../Developer/.../checkout/tests/swagger-ts-test/node_modules/tsoa/dist/metadataGeneration/typeResolver.js:207:136)
    at MethodGenerator.Generate (/Users/.../Developer/.../checkout/tests/swagger-ts-test/node_modules/tsoa/dist/metadataGeneration/methodGenerator.js:53:76)
    at /Users/.../Developer/.../checkout/tests/swagger-ts-test/node_modules/tsoa/dist/metadataGeneration/controllerGenerator.js:41:58
    at Array.map (<anonymous>)
    at ControllerGenerator.buildMethods (/Users/.../Developer/.../checkout/tests/swagger-ts-test/node_modules/tsoa/dist/metadataGeneration/controllerGenerator.js:41:14)
    at ControllerGenerator.Generate (/Users/.../Developer/.../checkout/tests/swagger-ts-test/node_modules/tsoa/dist/metadataGeneration/controllerGenerator.js:30:27)
```

## Steps to Reproduce

1. create the above model
2. set up for generating routes and swagger (version 2)
3. run command `tsoa swagger-and-routes`
4. see error output 

## Context (Environment)
Version of the library: 
Version of NodeJS: 
* Confirm you were using yarn not npm: [ ]

## Detailed Description
- tsoa.json
```
{
  "swagger": {
    "outputDirectory": "./app/swagger",
    "entryFile": "./src/app.ts",
    "host": "localhost:3000",
    "basePath": "/v1",
    "noImplicitAdditionalProperties": "silently-remove-extras",
    "securityDefinitions": {
      "api_key": {
        "type": "apiKey",
        "name": "access_token",
        "in": "query"
      },
      "tsoa_auth": {
        "type": "oauth2",
        "authorizationUrl": "http://swagger.io/api/oauth/dialog",
        "flow": "implicit",
        "scopes": {
          "write:pets": "modify things",
          "read:pets": "read things"
        }
      }
    },
    "yaml": false,
    "specVersion": 2
  },
  "routes": {
    "basePath": "/v1",
    "entryFile": "./src/app.ts",
    "routesDir": "./src/routes",
    "middleware": "express",
    "authenticationModule": "./src/auth/index.ts"
  }
}
```

- I used yomean with generator-express-ts to create the project

**Comment by sittingbool** [comment]
relates to https://github.com/lukeautry/tsoa/issues/563

**Comment by WoH** [comment]
I changed the title of #563, but since it's the same problem with the AST parser, I'll close this as a duplicate.
