### ISSUE TITLE
Error when creating routes, "False Expression"

### ISSUE THREAD

**Issue by Lev-Stambler** [lukeautry/tsoa#581]
## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [x] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

In the passed, tsoa routes and tsoa swagger worked as expected.

## Current Behavior

When I run ` tsoa routes ` or ` tsoa swagger `, I get a debug failure:

  ```
Generate routes error.
 Error: Debug Failure. False expression: Node must have a real position for this operation
    at NodeObject.assertHasRealPosition (/home/levst/code/talkmeup/talkmeup-v2-js/node_modules/typescript/lib/typescript.js:121339:22)
    at NodeObject.getFirstToken (/home/levst/code/talkmeup/talkmeup-v2-js/node_modules/typescript/lib/typescript.js:121390:18)
    at prettyLocationOfNode (/home/levst/code/talkmeup/talkmeup-v2-js/node_modules/tsoa/dist/metadataGeneration/exceptions.js:32:22)
    at new GenerateMetadataError (/home/levst/code/talkmeup/talkmeup-v2-js/node_modules/tsoa/dist/metadataGeneration/exceptions.js:23:46)
    at TypeResolver.resolve (/home/levst/code/talkmeup/talkmeup-v2-js/node_modules/tsoa/dist/metadataGeneration/typeResolver.js:184:19)
    at TypeResolver.resolve (/home/levst/code/talkmeup/talkmeup-v2-js/node_modules/tsoa/dist/metadataGeneration/typeResolver.js:100:137)
    at TypeResolver.resolve (/home/levst/code/talkmeup/talkmeup-v2-js/node_modules/tsoa/dist/metadataGeneration/typeResolver.js:207:136)
    at MethodGenerator.Generate (/home/levst/code/talkmeup/talkmeup-v2-js/node_modules/tsoa/dist/metadataGeneration/methodGenerator.js:53:76)
    at /home/levst/code/talkmeup/talkmeup-v2-js/node_modules/tsoa/dist/metadataGeneration/controllerGenerator.js:41:58
    at Array.map (<anonymous>)
error Command failed with exit code 1.
```

## Context (Environment)
Version of the library: 2.5.13
Version of NodeJS: v12.14.1
* Confirm you were using yarn not npm: [x]

**Comment by dgreene1** [comment]
Please fill out the “steps to reproduce” section so we can assist you. And ideally you would provide a repo with your code so we can try to reproduce the potential issue.

**Comment by WoH** [comment]
TSOA is failing on a virtual (inferred) type. Please specifically tell us what the inferred type is so we can fix the issue.
However, what's obvious is the symptom: We shouldn't try to call getText() on virtual types when we try to print them. Maybe there's a way to handle this more gracefully.

**Comment by Lev-Stambler** [comment]
@WoH the virtual types were the issue. All works now. Thank you!

**Comment by WoH** [comment]
Would be nice to see the the code with the inferred type that triggered the issue if you're able to provide an example.

**Comment by TimoGlastra** [comment]
I'm currently running into this issue when using generics in interfaces. I've managed to create a minimal example that produces this error.

The setup is just the plain setup from the tsoa docs, with a custom controller added:

```ts
import { Body, Controller, Post, Route } from "tsoa";

export interface ThePayload {
  name: string;
}

export interface TheInterface<T> {
  thePayload: T;
}

@Route("example")
export class ExampleController extends Controller {
  @Post()
  public async createUser(
    @Body()
    requestBody: TheInterface<ThePayload>
  ) {
    return requestBody;
  }
}
```

When running this tsoa will error with the following:

```
There was a problem resolving type of 'TheInterface<any>'.
Generate routes error.
 Error: Debug Failure. False expression: Node must have a real position for this operation
    at NodeObject.assertHasRealPosition (/Users/timo/Developer/Playground/tsoa/node_modules/typescript/lib/typescript.js:163908:22)
    at NodeObject.getText (/Users/timo/Developer/Playground/tsoa/node_modules/typescript/lib/typescript.js:163942:18)
    at /Users/timo/Developer/Playground/tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:692:103
    at Array.reduce (<anonymous>)
    at TypeResolver.contextualizedName (/Users/timo/Developer/Playground/tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:690:45)
    at TypeResolver.getReferenceType (/Users/timo/Developer/Playground/tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:575:27)
    at TypeResolver.resolve (/Users/timo/Developer/Playground/tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:389:36)
    at TypeResolver.resolve (/Users/timo/Developer/Playground/tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:386:129)
    at TypeResolver.propertyFromSignature (/Users/timo/Developer/Playground/tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:822:143)
    at /Users/timo/Developer/Playground/tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:788:125
```

Somehow the type of `ThePayload` is not picked up. Am I doing something wrong here? It seems like generics are supported. Happy to open a new issue for this if it is unrelated.

**Comment by huzaifahj** [comment]
@TimoGlastra Could you elaborate on what you mean by:

> It was because the return type wasn't explicitly declared.

What fix did you make to the code?

I am getting a similar error when using types from the `stripe` npm package.

```ts
import Stripe from "stripe"

let paymentMethods: Stripe.ApiList<Stripe.PaymentMethod>
```

### Error

```
There was a problem resolving type of 'ApiList<any>'.
Generate routes error.
 Error: Debug Failure. False expression: Node must have a real position for this operation
```
