### ISSUE TITLE
RFC: Support Links

### ISSUE THREAD

**Issue by WoH** [lukeautry/tsoa#712]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

OpenAPI 3 introduces [Links](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#linkObject):

> The Link object represents a possible design-time link for a response. The presence of a link does not guarantee the caller's ability to successfully invoke it, rather it provides a known relationship and traversal mechanism between responses and other operations.

Basically, you can use Links as a Specification driven approach to HATEOAS. Without putting all that info in every response payload, just use OAS Link.

> Unlike dynamic links (i.e. links provided in the response payload), the OAS linking mechanism does not require link information in the runtime response.

Furthermore, OAS Links allow specifying a response -> linked request parameter mapping:

> For computing links, and providing instructions to execute them, a runtime expression is used for accessing values in an operation and using them as parameters while invoking the linked operation.

For more examples, see [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#examples).

I'm not sure about the API we should use yet, but there are a few levels to get started.

In the simplest form, we can use a `@Links()` Decorator that links based on `operationId` (which corresponds to the controller method name in most cases) or `operationRef` (aka the path).

Not sure if there is a way to conveniently handle the res => req params mapping, ideally we could avoid writing JSON Pointers by hand :laughing: 

This is not a final proposal by any means, but if someone would a) use links b) has opinions on the API, any input is appreciated.

E: I should mention that last time I checked, documentation tooling support for links is mediocre at best, but I'd hope the Ecosystem will catch up soonTM.

**Comment by xavier-rodet** [comment]
Thumbs up, this is definitely something we need 👍 

I wonder why this feature has not been discussed in all this time...

**Comment by WoH** [comment]
Reopening this because TS now supports `@link` JSDoc.

**Comment by Kampfmoehre** [comment]
hi, I just want to add that tsoa currently has a problem when using @link in jsdoc. We had a @link pointing to a web URL and apparently tsoa tries to resolve it as code since we upgraded TypeScript from 4.2.4.

I am not sure if is intended to use @link tags for real web links so I won't open a bug for this. Just stumbled upon it and leave it here in case someone other also spends some time trying to find the reason for Tsoa to fail.

code looked like this
```ts
   /**
    * Generates a health report suitable for {@link https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks} UI.
    */
  @Get()
  @Response(503, "When the application is in an unhealthy state.")
  public async health(): Promise<HealthReport> {}
```
and produced an error like this:
```
Generate routes error.
 TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'SourceFileObject'
    |     property 'statements' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'NodeObject'
    --- property 'parent' closes the circle
    at JSON.stringify (<anonymous>)
    at <projectDir>/node_modules/@tsoa/cli/dist/module/generate-spec.js:72:29
    at step (<projectDir>/node_modules/@tsoa/cli/dist/module/generate-spec.js:33:23)
    at Object.next (<projectDir>/node_modules/@tsoa/cli/dist/module/generate-spec.js:14:53)
    at fulfilled (<projectDir>/node_modules/@tsoa/cli/dist/module/generate-spec.js:5:58)
```

**Comment by RadotJar** [comment]
Adding my support for this feature.
