### ISSUE TITLE
`Error: Unknown type: TypeLiteral` when model contains nested objects

### ISSUE THREAD

**Issue by Kjens93** [lukeautry/tsoa#73]
```
$ tsoa routes
There was a problem resolving type of 'Institution'.
Error: Unknown type: TypeLiteral
    at ResolveType (/Users/kjensen/.nvm/versions/node/v7.5.0/lib/node_modules/tsoa/dist/metadataGeneration/resolveType.js:27:15)
    at /Users/kjensen/.nvm/versions/node/v7.5.0/lib/node_modules/tsoa/dist/metadataGeneration/resolveType.js:137:23
    at Array.map (native)
    at getModelTypeProperties (/Users/kjensen/.nvm/versions/node/v7.5.0/lib/node_modules/tsoa/dist/metadataGeneration/resolveType.js:127:14)
    at generateReferenceType (/Users/kjensen/.nvm/versions/node/v7.5.0/lib/node_modules/tsoa/dist/metadataGeneration/resolveType.js:56:26)
    at ResolveType (/Users/kjensen/.nvm/versions/node/v7.5.0/lib/node_modules/tsoa/dist/metadataGeneration/resolveType.js:40:25)
    at Object.ResolveType (/Users/kjensen/.nvm/versions/node/v7.5.0/lib/node_modules/tsoa/dist/metadataGeneration/resolveType.js:38:16)
    at MethodGenerator.Generate (/Users/kjensen/.nvm/versions/node/v7.5.0/lib/node_modules/tsoa/dist/metadataGeneration/methodGenerator.js:23:34)
    at /Users/kjensen/.nvm/versions/node/v7.5.0/lib/node_modules/tsoa/dist/metadataGeneration/controllerGenerator.js:33:58
    at Array.map (native)
    at ControllerGenerator.buildMethods (/Users/kjensen/.nvm/versions/node/v7.5.0/lib/node_modules/tsoa/dist/metadataGeneration/controllerGenerator.js:33:14)
    at ControllerGenerator.Generate (/Users/kjensen/.nvm/versions/node/v7.5.0/lib/node_modules/tsoa/dist/metadataGeneration/controllerGenerator.js:23:27)
    at /Users/kjensen/.nvm/versions/node/v7.5.0/lib/node_modules/tsoa/dist/metadataGeneration/metadataGenerator.js:47:58
    at Array.map (native)
    at MetadataGenerator.buildControllers (/Users/kjensen/.nvm/versions/node/v7.5.0/lib/node_modules/tsoa/dist/metadataGeneration/metadataGenerator.js:47:14)
    at MetadataGenerator.Generate (/Users/kjensen/.nvm/versions/node/v7.5.0/lib/node_modules/tsoa/dist/metadataGeneration/metadataGenerator.js:22:32)
```

Here's my controller:
```typescript
import { Institution } from "../model/Institution";
import { Controller, Route, Get } from "tsoa";
import { MockInstitutionsService } from "../service/MockInstitutionsService";
import { InstitutionsService } from "../service/InstitutionsService";

@Route("institutions")
export class InstitutionsController extends Controller {

  service: InstitutionsService = new MockInstitutionsService();

  @Get("{id}")
  public async findById(id: string): Promise<Institution> {
    return await this.service.findById(id);
  }

}
```

Here's my model:
```typescript
export interface Institution {
  id: string,
  name: string,
  logo: string,
  colors: {
    primary: string,
    gradient: string[]
  }
}
```

Here's my `tsoa.json`:
```json
{
  "swagger": {
    "outputDirectory": "./dist",
    "entryFile": "./src/index.ts",
    "host": "localhost:3000",
    "basePath": "/v1"
  },
  "routes": {
    "basePath": "/v1",
    "entryFile": "./src/index.ts",
    "routesDir": "./src",
    "middleware": "express"
  }
}
```

**Comment by Kjens93** [comment]
It looks like the problem is with the nested `colors` property of the `Institution` interface. The above works if I create a new interface, `InstitutionColors` and change `colors: {...}` to `colors: InstitutionColors`. The framework should be able to take care of this for me.

**Comment by Dirrk** [comment]
> The framework should be able to take care of this for me.

@Kjens93, personally I would disagree that any framework should declare your interfaces for you.

This library allows you to declare your interfaces, and then it uses that metadata to automate the routes/swagger definition.  

While its very possible for it to do it for you, wouldn't you want to be notified if you didn't declare your interface properly?  In particular with this library, you are declaring the contract for other developers to use.  Wouldn't it make more sense to have a InstitutionColors interface/class that can be modified in one place that updates all requests/responses that use it?

Just my opinion tho.

**Comment by lukeautry** [comment]
I think this is a valid issue. There's an issue open for it currently: https://github.com/lukeautry/tsoa/issues/50

I've been meaning to get to this. Will hopefully have a fix in the next week or so.
