### ISSUE TITLE
Issues while setting up dev environment to contribute

### ISSUE THREAD

**Issue by tsimbalar** [lukeautry/tsoa#733]
I'd like to contribute on some "up for grabs" issues. I started by forking / cloning the repo, and wanted to run the tests locally to understand how the codebase is organized.

I haven't managed to run the tests yet.

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
On a clean checkout, I should be able to do : 

```
yarn install
yarn test
```

and have the tests running

## Current Behavior

When doing `yarn test` , I get : 

```
yarn test
yarn run v1.22.4
$ cross-env NODE_ENV=tsoa_test ts-node ./tests/prepare.ts

/Users/yc00067/.nvm/versions/node/v12.16.1/lib/node_modules/ts-node/src/index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
tests/prepare.ts:2:19 - error TS2307: Cannot find module 'chalk' or its corresponding type declarations.

2 import chalk from 'chalk';
                    ~~~~~~~

    at createTSError (/Users/yc00067/.nvm/versions/node/v12.16.1/lib/node_modules/ts-node/src/index.ts:434:12)
    at reportTSError (/Users/yc00067/.nvm/versions/node/v12.16.1/lib/node_modules/ts-node/src/index.ts:438:19)
    at getOutput (/Users/yc00067/.nvm/versions/node/v12.16.1/lib/node_modules/ts-node/src/index.ts:578:36)
    at Object.compile (/Users/yc00067/.nvm/versions/node/v12.16.1/lib/node_modules/ts-node/src/index.ts:775:32)
    at Module.m._compile (/Users/yc00067/.nvm/versions/node/v12.16.1/lib/node_modules/ts-node/src/index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/yc00067/.nvm/versions/node/v12.16.1/lib/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Steps to Reproduce

1. `yarn install`
2. `yarn test`

## Context (Environment)

Version of the library: checked out master / commit 29cb3c2d80c6ebe9198c1e1fbdbba2750beb1973 
Version of NodeJS: 12.16.1

- Confirm you were using yarn not npm: [x]

Running on macOS 10.14.6 (18G2022) 
I have `nvm` installed as well

I'm quite familiar with `npm` but have close to 0 knowledge about `yarn`. 

I initially started with some errors about `cross-env` not existing, which I fixed by installing it via `npm i -g cross-env`.

Then I got this error : 

```
> yarn run test
yarn run v1.22.4
$ cross-env NODE_ENV=tsoa_test ts-node ./tests/prepare.ts
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: spawn ts-node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ts-node',
  path: 'ts-node',
  spawnargs: [ './tests/prepare.ts' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I installed `ts-node` globally via `npm i -g ts-node` and after that I got the error mentioned above.

Am I expected to install a bunch of libraries globally on my machine ? Is it maybe documented somewhere and I have missed it ? 

Once I can figure it out, I'd be happy to maybe update the `CONTRIBUTING.md` guide to add more details about pre-requisited of the dev machine.

Thanks a lot !

**Comment by tsimbalar** [comment]
Ok this is just silly, and I have been getting crazy about it.

Not 100% sure how that happened (maybe successive installations of `yarn` through `npm` or through `brew` have messed up my terminal) ... but turns out I was running with `NODE_ENV=production` for some reason ... 

Therefore `yarn` was not installing all the `dev` dependencies 🤦 .

Mystery solved, I guess. 

Sorry about that :)
