### ISSUE TITLE
Error 'request.header is not a function' on @Header decorator

### ISSUE THREAD

**Issue by gabrielhamel** [lukeautry/tsoa#744]
In my controller, I'm trying to get some headers params
```js
@Get('login')
public async login(
        @Header('applicationid') applicationId: string,
        @Header() email: string,
        @Header() password: string
    ): Promise<LoginDTO> {
    return await this.authService.login(applicationId, email, password);
}
```
But i get this stack trace
```
TypeError: request.header is not a function
    at /Users/gabriel/Documents/axociation-backend/_gen/routes/routes.ts:419:79
    at Array.map (<anonymous>)
    at getValidatedArgs (/Users/gabriel/Documents/axociation-backend/_gen/routes/routes.ts:409:42)
    at /Users/gabriel/Documents/axociation-backend/_gen/routes/routes.ts:242:33
    at runNext (/Users/gabriel/Documents/axociation-backend/src/router.ts:35:17)
    at /Users/gabriel/Documents/axociation-backend/src/router.ts:69:13
    at Layer.handle [as handle_request] (/Users/gabriel/Documents/axociation-backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/gabriel/Documents/axociation-backend/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/gabriel/Documents/axociation-backend/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/gabriel/Documents/axociation-backend/node_modules/express/lib/router/layer.js:95:5)
    at /Users/gabriel/Documents/axociation-backend/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/gabriel/Documents/axociation-backend/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/gabriel/Documents/axociation-backend/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/gabriel/Documents/axociation-backend/node_modules/express/lib/router/index.js:174:3)
    at handler (/Users/gabriel/Documents/axociation-backend/src/router.ts:87:21)
    at InProcessRunner.run (/Users/gabriel/Documents/axociation-backend/node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/InProcessRunner.js:100:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at LambdaFunction.runHandler (/Users/gabriel/Documents/axociation-backend/node_modules/serverless-offline/dist/lambda/LambdaFunction.js:318:20)
    at hapiHandler (/Users/gabriel/Documents/axociation-backend/node_modules/serverless-offline/dist/events/http/HttpServer.js:457:18)
    at module.exports.internals.Manager.execute (/Users/gabriel/Documents/axociation-backend/node_modules/@hapi/hapi/lib/toolkit.js:45:28)
    at Object.internals.handler (/Users/gabriel/Documents/axociation-backend/node_modules/@hapi/hapi/lib/handler.js:46:20)
    at exports.execute (/Users/gabriel/Documents/axociation-backend/node_modules/@hapi/hapi/lib/handler.js:31:20)
    at Request._lifecycle (/Users/gabriel/Documents/axociation-backend/node_modules/@hapi/hapi/lib/request.js:312:32)
    at Request._execute (/Users/gabriel/Documents/axociation-backend/node_modules/@hapi/hapi/lib/request.js:221:9)
```
in the routes.ts at line 419:
```
case 'header':
    return validationService.ValidateParam(args[key], request.header(name), name, fieldErrors, undefined, { "noImplicitAdditionalProperties": "throw-on-extras" });
```
I am using TSOA latest version (3.2.1) with Serverless.
Thanks if you find a solution 😀

**Comment by gabrielhamel** [comment]
Okay, I found the solution.
Isn't the an Tsoa problem.
I'm currently using this fork https://github.com/rquast/tsoa-serverless-example
with his own implementation of Express.
The HttpRequest object doesn't have headers function.
