### ISSUE TITLE
yarn run tsoa routes - returns error

### ISSUE THREAD

**Issue by zaalgol** [lukeautry/tsoa#873]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

running 'yarn run tsoa routes' should create routes.ts file

## Current Behavior
error msg:

    yarn run v1.22.5
    $ C:\tsoa-project\node_modules\.bin\tsoa routes
    Generate routes error.
     Error: ENOENT: no such file or directory, lstat 'build'
        at Object.lstatSync (fs.js:1077:3)
        at RouteGenerator.<anonymous> (C:\tsoa-project\node_modules\@tsoa\cli\dist\routeGeneration\routeGenerator.js:69:33)
        at step (C:\tsoa-project\node_modules\@tsoa\cli\dist\routeGeneration\routeGenerator.js:44:23)
        at Object.next (C:\tsoa-project\node_modules\@tsoa\cli\dist\routeGeneration\routeGenerator.js:25:53)
        at C:\tsoa-project\node_modules\@tsoa\cli\dist\routeGeneration\routeGenerator.js:19:71
        at new Promise (<anonymous>)
        at __awaiter (C:\tsoa-project\node_modules\@tsoa\cli\dist\routeGeneration\routeGenerator.js:15:12)
        at RouteGenerator.GenerateRoutes (C:\tsoa-project\node_modules\@tsoa\cli\dist\routeGeneration\routeGenerator.js:64:16)
        at RouteGenerator.<anonymous> (C:\tsoa-project\node_modules\@tsoa\cli\dist\routeGeneration\routeGenerator.js:94:51)
        at step (C:\tsoa-project\node_modules\@tsoa\cli\dist\routeGeneration\routeGenerator.js:44:23) {
      errno: -4058,
      syscall: 'lstat',
      code: 'ENOENT',
      path: 'build'
    }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

## Steps to Reproduce

implement step by step the example in [https://tsoa-community.github.io/docs/getting-started.html#initializing-our-project](https://tsoa-community.github.io/docs/getting-started.html#initializing-our-project)

this is the scripts section in my C:\tsoa-project\package.json file:

    "scripts": {
        "build": "tsoa spec-and-routes && tsc",
        "start": "node build/src/server.js"
      }

## Context (Environment)

Version of the library: 3.4.0
Version of NodeJS: 6.14.9

- Confirm you were using yarn not npm: [x]

**Comment by WoH** [comment]
As the error message says, it seems like you don't have a build/ directory in your project. If you're sure you haven't skipped any commands or setup steps, please file an issue or send a PR to [the docs repo](https://github.com/tsoa-community/docs/issues).
