### ISSUE TITLE
There was a problem resolving type of 'Map'.

### ISSUE THREAD

**Issue by jawpio** [lukeautry/tsoa#92]
```
There was a problem resolving type of 'Map'.
There was a problem resolving type of 'Product'.
Error: No matching model found for referenced type Map
    at getModelTypeDeclaration (/Users/projects/tsoa-example-master/node_modules/tsoa/dist/metadataGeneration/resolveType.js:309:15)
    at getReferenceType (/Users/projects/papi3/tsoa-example-master/node_modules/tsoa/dist/metadataGeneration/resolveType.js:172:36)
    at ResolveType (/Users/projects/papi3/tsoa-example-master/node_modules/tsoa/dist/metadataGeneration/resolveType.js:59:25)
    at /Users/projects/papi3/tsoa-example-master/node_modules/tsoa/dist/metadataGeneration/resolveType.js:391:19
    at Array.map (native)
    at getModelTypeProperties (/Users/projects/papi3/tsoa-example-master/node_modules/tsoa/dist/metadataGeneration/resolveType.js:382:10)
    at getReferenceType (/Users/projects/papi3/tsoa-example-master/node_modules/tsoa/dist/metadataGeneration/resolveType.js:173:26)
    at ResolveType (/Users/projects/papi3/tsoa-example-master/node_modules/tsoa/dist/metadataGeneration/resolveType.js:59:25)
    at Object.ResolveType (/Users/projects/papi3/tsoa-example-master/node_modules/tsoa/dist/metadataGeneration/resolveType.js:42:20)
    at MethodGenerator.Generate (/Users/projects/papi3/tsoa-example-master/node_modules/tsoa/dist/metadataGeneration/methodGenerator.js:24:34)
    at /Users/projects/papi3/tsoa-example-master/node_modules/tsoa/dist/metadataGeneration/controllerGenerator.js:33:58
    at Array.map (native)
    at ControllerGenerator.buildMethods (/Users/projects/papi3/tsoa-example-master/node_modules/tsoa/dist/metadataGeneration/controllerGenerator.js:33:14)
    at ControllerGenerator.Generate (/Users/projects/papi3/tsoa-example-master/node_modules/tsoa/dist/metadataGeneration/controllerGenerator.js:23:27)
    at /Users/projects/papi3/tsoa-example-master/node_modules/tsoa/dist/metadataGeneration/metadataGenerator.js:47:58
    at Array.map (native)
```

the model:
```
export class Product {
    public id: string;
    public name: string;
    public metaData: Map<string, string>;
}
```

The controller and tsoa configuration are generally ok, when I remove the metadata all is working fine.
I tried to overcome the problem by defining metaData as `public metaData: { [key: string]: string; };` unfortunately no luck here I think this is connected with #50.

I had the same issue with type `Array<string>`, I was able to overcome this by defining type as `string[]`.

**Comment by dexhorthy** [comment]
@jawpio  FWIW I found a small workaround that might help.

I had a similar issue with something like 

```
export interface Product {
  fields: { [key: string]: string; };
}
```

and found that TSOA works if you create a type for the field:

```
export interface Fields {
  [key: string]: string;
}

export interface Product {
  fields: Fields;
}

```

This worked for interfaces at least, might work for classes. I think it has something to do with how the swagger generator handles anonymous types.

**Comment by lukeautry** [comment]
Hmm...what does your tsconfig look like?

**Comment by jawpio** [comment]
@lukeautry I based on your sample project, the config is super simple.
```
{
    "compilerOptions": {
        "outDir": "./dist",
        "rootDir": "./src",
        "sourceMap": true,
        "module": "commonjs",
        "target": "es6",
        "experimentalDecorators": true
    }
}
```

**Comment by lukeautry** [comment]
Looks like this is basically the same as #372 . Closing this one.
